
#Config to adjust world settings
[World]
	#Enable the villager structures for the computer scientist.
	enableVillagerStructures = false
	#Gives the ap documentation to new players on a world.
	givePlayerBookOnJoin = false
	#The weight of the villager structures
	#Range: 0 ~ 16000
	villagerStructureWeight = 10

