
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 2500000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 500000
	#Range: 0 ~ 9000000000000000000
	basicCap = 25000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 1000000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 8000000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 100000
	#Range: 0 ~ 9000000000000000000
	starterCap = 5000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 2000
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 50
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 150
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 300
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 1000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 700
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 4000

[Energy_Generation]
	#Range: 0 ~ 9000000000000000000
	blazingGeneration = 90
	#Range: 0 ~ 9000000000000000000
	starterGeneration = 5
	#Range: 0 ~ 9000000000000000000
	nitroGeneration = 1200
	#Range: 0 ~ 9000000000000000000
	hardenedGeneration = 40
	#Range: 0 ~ 9000000000000000000
	spiritedGeneration = 500
	#Range: 0 ~ 9000000000000000000
	basicGeneration = 12
	#Range: 0 ~ 9000000000000000000
	nioticGeneration = 220

