
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 0
	#Range: 0 ~ 9000000000000000000
	blazingCap = 0
	#Range: 0 ~ 9000000000000000000
	basicCap = 0
	#Range: 0 ~ 9000000000000000000
	nioticCap = 0
	#Range: 0 ~ 9000000000000000000
	nitroCap = 0
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 0
	#Range: 0 ~ 9000000000000000000
	starterCap = 0

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 100000
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 200
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 2500
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 8000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 50000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 20000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 400000

[Channels]
	#Range: 1 ~ 12
	hardenedChannels = 3
	#Range: 1 ~ 12
	basicChannels = 2
	#Range: 1 ~ 12
	spiritedChannels = 9
	#Range: 1 ~ 12
	starterChannels = 1
	#Range: 1 ~ 12
	nioticChannels = 7
	#Range: 1 ~ 12
	blazingChannels = 5
	#Range: 1 ~ 12
	nitroChannels = 12

