
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 15000000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 5000000
	#Range: 0 ~ 9000000000000000000
	basicCap = 1000000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 10000000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 40000000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 3000000
	#Range: 0 ~ 9000000000000000000
	starterCap = 100000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 100000
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 500
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 2500
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 8000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 50000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 20000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 400000

[Charging_Speed]
	#Range: 0 ~ 9000000000000000000
	nitroChargingSpeed = 50000
	#Range: 0 ~ 9000000000000000000
	blazingChargingSpeed = 8000
	#Range: 0 ~ 9000000000000000000
	basicChargingSpeed = 1000
	#Range: 0 ~ 9000000000000000000
	hardenedChargingSpeed = 3000
	#Range: 0 ~ 9000000000000000000
	nioticChargingSpeed = 12000
	#Range: 0 ~ 9000000000000000000
	spiritedChargingSpeed = 20000
	#Range: 0 ~ 9000000000000000000
	starterChargingSpeed = 100

