#No comment
#Range: 1 ~ 32
range = 4

[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	starterCap = 10000
	#Range: 0 ~ 9000000000000000000
	basicCap = 100000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 250000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 800000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 1500000
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 4000000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 10000000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 10
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 50
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 135
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 450
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 2100
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 14000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 154000

