
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 0
	#Range: 0 ~ 9000000000000000000
	blazingCap = 0
	#Range: 0 ~ 9000000000000000000
	basicCap = 0
	#Range: 0 ~ 9000000000000000000
	nioticCap = 0
	#Range: 0 ~ 9000000000000000000
	nitroCap = 0
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 0
	#Range: 0 ~ 9000000000000000000
	starterCap = 0

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 90000
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 100
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 1400
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 5000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 40000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 18000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 200000

