
[general]
	#The material blacklist of this module.
	materialBlacklist = ["mana", "bitumen", "dimensional"]
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = []

