
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have pulverizer recipes added.
	toDustMaterialBlacklist = []
	#The materials that should not have create compat recipes added.
	createToIngotMaterialBlacklist = []
	#The materials that should not have press to gear recipes added.
	toGearMaterialBlacklist = []
	#The materials that should not have smelter recipes added.
	toIngotMaterialBlacklist = []
	#The materials that should not have press to coin recipes added.
	toCoinMaterialBlacklist = []
	#The materials that should not have press to plate recipes added.
	toPlateMaterialBlacklist = []

