#The title to display at the top of the entry.
title = "Need a server?"
#The description to display below the title.
description = "Click me to get your own server!"
#Your affiliate ID to use in during the ordering process.
#Without this you will not be credited for the purchases.
#(Your affiliate id is not the same as your referral link, please check your client area to find your affiliate id at https://www.bisecthosting.com/partners/console.php).
affiliate_id = "2214"
#The id of this modpack.
#(This is BH internal pack id; Find the id here: https://www.bisecthosting.com/partners/console.php)
pack_id = "17658"

