
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	starterCap = 60000
	#Range: 0 ~ 9000000000000000000
	basicCap = 90000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 120000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 150000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 180000
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 210000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 240000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 18000
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 36000
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 60000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 90000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 150000
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 240000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 360000

[Energy_Generation]
	#Range: 0 ~ 9000000000000000000
	starterGeneration = 360
	#Range: 0 ~ 9000000000000000000
	basicGeneration = 390
	#Range: 0 ~ 9000000000000000000
	hardenedGeneration = 420
	#Range: 0 ~ 9000000000000000000
	blazingGeneration = 450
	#Range: 0 ~ 9000000000000000000
	nioticGeneration = 480
	#Range: 0 ~ 9000000000000000000
	spiritedGeneration = 510
	#Range: 0 ~ 9000000000000000000
	nitroGeneration = 540

