
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	basicCap = 4000000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 10000000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 18000000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 30000000
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 50000000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 80000000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 50000
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 100000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 140000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 160000
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 400000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 800000

[Energy_Generation]
	#Range: 0 ~ 9000000000000000000
	basicGeneration = 600
	#Range: 0 ~ 9000000000000000000
	hardenedGeneration = 1260
	#Range: 0 ~ 9000000000000000000
	blazingGeneration = 1800
	#Range: 0 ~ 9000000000000000000
	nioticGeneration = 4050
	#Range: 0 ~ 9000000000000000000
	spiritedGeneration = 5700
	#Range: 0 ~ 9000000000000000000
	nitroGeneration = 8100

