
[modules]

	[modules.resources]
		enabled = true

		[modules.resources.gold]

			[modules.resources.gold.gear]
				enabled = true

		[modules.resources.diamond]

			[modules.resources.diamond.gear]
				enabled = true

		[modules.resources.iron]

			[modules.resources.iron.gear]
				enabled = true

