
[TitaniumConfig]
	#A Boolean that is true by default
	thisIsABoolean = true
	intAngery = 7
	#A Boolean that is false by default
	NOT_BOOLEAN = false

	[TitaniumConfig.Dabber]
		dabby = "lil dab"

	[TitaniumConfig.TestBlock]
		DUMB_VALUE = 135

