
#Client Config. This config only exists on the client
[client]
	#Set to false to prevent particle spam when loading multiblocks (notification message will display instead).
	enableMultiblockFormationParticles = true
	#If enabled machines play their sounds while running.
	enableMachineSounds = true
	#Play sounds for Jetpack/Gas Mask/Flamethrower/Radiation (all players).
	enablePlayerSounds = true
	#Adjust Mekanism sounds' base volume. < 1 is softer, higher is louder.
	#Range: 0.0 ~ 3.4028234663852886E38
	baseSoundVolume = 1.0
	#Range at which Tile Entity Renderer's added by Mekanism can render at, for example the contents of multiblocks. Vanilla defaults the rendering range for TERs to 64 for most blocks, but uses a range of 256 for beacons and end gateways.
	#Range: 1 ~ 1024
	terRange = 256
	#How many particles spawn when rendering radiation effects (scaled by radiation level).
	radiationParticleCount = 100
	#Show particles when machines active.
	machineEffects = true
	#Enable item information HUD during gameplay
	enableHUD = true
	#Allow sneak + scroll to change item modes.
	allowModeScroll = true
	#Should active machines produce block light.
	enableAmbientLighting = true
	#If true, don't render Cables/Pipes/Tubes as transparent and don't render their contents.
	opaqueTransmitters = false
	#Christmas/New Years greetings in chat.
	holidays = true
	#Color of energy in item durability display.
	energyColor = 3997338
	#How far (in blocks) from the player radiation particles can spawn.
	radiationParticleRadius = 30
	#Align HUD with left (if true) or right (if false)
	alignHUDLeft = true
	#How much light to produce if ambient lighting is enabled.
	#Range: 1 ~ 15
	ambientLightingLevel = 15

	#QIO Config
	[client.qio]
		#Sorting direction when viewing items in a QIO Item Viewer.
		#Allowed Values: ASCENDING, DESCENDING
		itemViewerSortDirection = "ASCENDING"
		#Sorting strategy when viewing items in a QIO Item Viewer.
		#Allowed Values: NAME, SIZE, MOD
		itemViewerSortType = "NAME"
		#Number of slots to view horizontally on a QIO Item Viewer.
		#Range: 8 ~ 16
		itemViewerSlotsX = 8
		#Number of slots to view vertically on a QIO Item Viewer.
		#Range: 2 ~ 48
		itemViewerSlotsY = 4

	#GUI Config
	[client.gui]
		#Color of HUD used by MekaSuit.
		hudColor = 4257264
		#Display a fancy compass when the MekaSuit is worn.
		mekaSuitHelmetCompass = true
		#Opacity of HUD used by MekaSuit.
		#Range: 0.0 ~ 1.0
		hudOpacity = 0.4000000059604645
		#Visual jitter of MekaSuit HUD, seen when moving the player's head. Bigger value = more jitter.
		#Range: 1.0 ~ 100.0
		hudJitter = 6.0
		#Color of warning HUD elements used by MekaSuit.
		hudWarningColor = 16768335
		#Color of danger HUD elements used by MekaSuit.
		hudDangerColor = 16726076

