
#Gear Config. This config is synced from server to client.
[gear]

	#MekaSuit Settings
	[gear.mekasuit]
		#Maximum amount of Nutritional Paste storable by the nutritional injection unit.
		#Range: 1 ~ 9223372036854775807
		nutritionalMaxStorage = 128000
		#Energy usage (Joules) of MekaSuit per tick when flying via Gravitational Modulation.
		energyUsageGravitationalModulation = "1000"
		#Energy cost/multiplier in Joules for reducing magic damage via the inhalation purification unit. Energy cost is: MagicDamage * energyUsageMagicPrevent. (1 MagicDamage is 1 half heart).
		energyUsageMagicReduce = "1000"
		#Energy usage (Joules) of MekaSuit when adding 0.1 to jump motion.
		baseJumpEnergyUsage = "1000"
		#Energy usage (Joules) of MekaSuit per tick of using vision enhancement.
		energyUsageVisionEnhancement = "500"
		#Solar recharging rate (Joules) of helmet per tick, per upgrade installed.
		solarRechargingRate = "500"
		#Energy usage (Joules) of MekaSuit per tick of attracting a single item.
		energyUsageItemAttraction = "250"
		#Energy usage (Joules) of MekaSuit when adding 0.1 to sprint motion.
		energyUsageSprintBoost = "100"
		#Maximum amount of Hydrogen storable in the jetpack unit.
		#Range: 1 ~ 9223372036854775807
		jetpackMaxStorage = 48000
		#Rate at which Hydrogen can be transferred into the jetpack unit.
		#Range: 1 ~ 9223372036854775807
		jetpackTransferRate = 256
		#Energy usage (Joules) of MekaSuit when lessening a potion effect.
		energyUsagePotionTick = "40000"
		#Energy capacity (Joules) of MekaSuit items without any installed upgrades. Quadratically scaled by upgrades.
		baseEnergyCapacity = "16000000"
		#Amount (joules) of energy the MekaSuit can accept per tick. Quadratically scaled by upgrades.
		chargeRate = "100000"
		#Energy usage (Joules) of MekaSuit per unit of damage applied.
		energyUsageDamage = "100000"
		#Rate at which Nutritional Paste can be transferred into the nutritional injection unit.
		#Range: 1 ~ 9223372036854775807
		nutritionalTransferRate = 256
		#Charge rate of inventory items (Joules) per tick.
		inventoryChargeRate = "10000"
		#Energy usage (Joules) of MekaSuit per half-food of nutritional injection.
		energyUsageNutritionalInjection = "20000"

	#Network Reader Settings
	[gear.network_reader]
		#Maximum amount (joules) of energy the Network Reader can contain.
		maxEnergy = "60000"
		#Amount (joules) of energy the Network Reader can accept per tick.
		chargeRate = "300"
		#Energy usage in joules for each network reading.
		energyUsage = "400"

	#Free Runner Settings
	[gear.free_runner]
		#Maximum amount (joules) of energy Free Runners can contain.
		maxEnergy = "64000"
		#Amount (joules) of energy the Free Runners can accept per tick.
		chargeRate = "320"
		#Energy cost/multiplier in Joules for reducing fall damage with free runners. Energy cost is: FallDamage * freeRunnerFallEnergyCost. (1 FallDamage is 1 half heart)
		fallEnergyCost = "50"

	#Portable Teleporter Settings
	[gear.portable_teleporter]
		#Maximum amount (joules) of energy the Portable Teleporter can contain.
		maxEnergy = "1000000"
		#Amount (joules) of energy the Portable Teleporter can accept per tick.
		chargeRate = "5000"
		#Delay in ticks before a player is teleported after clicking the Teleport button in the portable teleporter.
		delay = 0

	#Atomic Disassembler Settings
	[gear.atomic_disassembler]
		#Maximum amount (joules) of energy the Atomic Disassembler can contain.
		maxEnergy = "1000000"
		#Amount (joules) of energy the Atomic Disassembler can accept per tick.
		chargeRate = "5000"
		#Cost in Joules of using the Atomic Disassembler as a weapon.
		energyUsageWeapon = "2000"
		#Base Energy (Joules) usage of the Atomic Disassembler. (Gets multiplied by speed factor)
		energyUsage = "10"
		#Enable the 'Slow' mode for the Atomic Disassembler.
		slowMode = true
		#Enable the 'Fast' mode for the Atomic Disassembler.
		fastMode = true
		#Enable the 'Vein Mining' mode for the Atomic Disassembler.
		veinMining = true
		#The amount of damage the Atomic Disassembler does when it has at least DisassemblerEnergyUsageWeapon power stored. (Value is in number of half hearts)
		maxDamage = 20
		#The max Atomic Disassembler Vein Mining Block Count.
		miningCount = 128
		#The Range of the Atomic Disassembler Extended Vein Mining.
		miningRange = 10
		#Enable the 'Extended Vein Mining' mode for the Atomic Disassembler. (Allows vein mining everything not just ores/logs)
		extendedMining = true
		#The amount of damage the Atomic Disassembler does when it is out of power. (Value is in number of half hearts)
		minDamage = 4

	#Energy Tablet Settings
	[gear.energy_tablet]
		#Maximum amount (joules) of energy the Energy Tablet can contain.
		maxEnergy = "1000000"
		#Amount (joules) of energy the Energy Tablet can accept per tick.
		chargeRate = "5000"

	#Configurator Settings
	[gear.configurator]
		#Maximum amount (joules) of energy the Configurator can contain.
		maxEnergy = "60000"
		#Amount (joules) of energy the Configurator can accept per tick.
		chargeRate = "300"
		#Energy usage in joules of using the configurator to configure machines.
		energyPerConfigure = "400"
		#Energy cost in joules for each item the configurator ejects from a machine on empty mode.
		energyPerItem = "8"

	#Scuba Tank Settings
	[gear.scuba_tank]
		#Amount of oxygen the Scuba Tank Gas Tank can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 16
		#Scuba Tank Gas Tank capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 24000

	#Electric Bow Settings
	[gear.electric_bow]
		#Maximum amount (joules) of energy the Electric Bow can contain.
		maxEnergy = "120000"
		#Amount (joules) of energy the Electric Bow can accept per tick.
		chargeRate = "600"
		#Cost in Joules of using the Electric Bow with flame mode active.
		energyUsage = "1200"

	#Flamethrower Settings
	[gear.flamethrower]
		#Amount of hydrogen the Flamethrower can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 16
		#Flamethrower Gas Tank capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 24000

	#Jetpack Settings
	[gear.jetpack]
		#Amount of hydrogen the Jetpack can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 16
		#Jetpack Gas Tank capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 24000

		#Armored Jetpack Settings
		[gear.jetpack.armored]
			#Armor value of the Armored Jetpack.
			armor = 12
			#Toughness value of the Armored Jetpack.
			toughness = 2.0

	#Canteen Settings
	[gear.canteen]
		#Rate at which Nutritional Paste can be transferred into a Canteen.
		#Range: 1 ~ 9223372036854775807
		transferRate = 128
		#Maximum amount of Nutritional Paste storable by the Canteen.
		#Range: 1 ~ 9223372036854775807
		maxStorage = 64000

	#Seismic Reader Settings
	[gear.seismic_reader]
		#Maximum amount (joules) of energy the Seismic Reader can contain.
		maxEnergy = "12000"
		#Amount (joules) of energy the Seismic Reader can accept per tick.
		chargeRate = "60"
		#Energy usage in joules required to use the Seismic Reader.
		energyUsage = "250"

	#Meka-Tool Settings
	[gear.mekatool]
		#Energy capacity (Joules) of the Meka-Tool without any installed upgrades. Quadratically scaled by upgrades.
		baseEnergyCapacity = "16000000"
		#Amount (joules) of energy the Meka-Tool can accept per tick. Quadratically scaled by upgrades.
		chargeRate = "100000"
		#Cost in Joules of using the Meka-Tool to teleport 10 blocks.
		energyUsageTeleport = "1000"
		#Cost in Joules of using the Meka-Tool as a shovel for making paths.
		energyUsageShovel = "10"
		#Cost in Joules of using the Meka-Tool to deal 4 units of damage.
		energyUsageWeapon = "2000"
		#Cost in Joules of using the Meka-Tool as a hoe.
		energyUsageHoe = "10"
		#Cost in Joules of using the Meka-Tool as an axe for stripping logs.
		energyUsageAxe = "10"
		#Maximum distance a player can teleport with the Meka-Tool.
		maxTeleportReach = 100
		#Damage applied by Meka-Tool without using any energy.
		baseDamage = 4
		#Efficiency of the Meka-Tool with energy but without any upgrades.
		baseEfficiency = 4.0
		#Enable the 'Extended Vein Mining' mode for the Meka-Tool. (Allows vein mining everything not just ores/logs)
		extendedMining = true

