
#Mekanism Generators Config. This config is synced between server and client.
[generators]
	#Peak output for the Advanced Solar Generator. Note: It can go higher than this value in some extreme environments.
	advancedSolarGeneration = "300"
	#Affects the Injection Rate, Max Temp, and Ignition Temp.
	energyPerFusionFuel = "10000000"
	#Amount of energy in Joules the Bio Generator produces per tick.
	bioGeneration = "350"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	solarGeneration = "50"

	#Wind Generator Settings
	[generators.wind_generator]
		#Minimum base generation value of the Wind Generator.
		windGenerationMin = "60"
		#The list of dimension ids that the Wind Generator will not generate power in.
		windGenerationDimBlacklist = []
		#The maximum Y value that affects the Wind Generators Power generation.
		windGenerationMaxY = 255
		#Maximum base generation value of the Wind Generator.
		windGenerationMax = "480"
		#The minimum Y value that affects the Wind Generators Power generation.
		windGenerationMinY = 24

	#Turbine Settings
	[generators.turbine]
		#The number of blades on each turbine coil per blade applied.
		turbineBladesPerCoil = 4
		#The rate at which steam is vented into the turbine.
		turbineVentGasFlow = 32000.0
		#The rate at which steam is dispersed into the turbine.
		turbineDisperserGasFlow = 1280.0
		#The rate at which steam is condensed in the turbine.
		condenserRate = 64000

	#Heat Generator Settings
	[generators.heat_generator]
		#Add this amount of Joules to the energy produced by a heat generator if it is in an 'ultrawarm' dimension, in vanilla this is just the Nether.
		heatGenerationNether = "100"
		#Multiplier of effectiveness of Lava in the Heat Generator.
		heatGenerationLava = "30"
		#Amount of energy in Joules the Heat Generator produces per tick. (heatGenerationLava * heatGenerationLava) + heatGenerationNether
		heatGeneration = "200"

	#Fission Reactor Settings
	[generators.fission_reactor]
		#The heat capacity added to a Fission Reactor by a single casing block. Increase to require more energy to raise the reactor temperature.
		casingHeatCapacity = 1000.0
		#The chance of a meltdown occurring once damage passes 100%. Will linearly scale as damage continues increasing.
		#Range: 0.0 ~ 1.0
		meltdownChance = 0.001
		#Whether catastrophic meltdowns can occur from Fission Reactors.
		meltdownsEnabled = true
		#How much radioactivity of fuel/waste contents are multiplied during a meltdown.
		meltdownRadiationMultiplier = 50.0
		#The average surface area of a Fission Reactor's fuel assemblies to reach 100% boil efficiency. Higher values make it harder to cool the reactor.
		#Range: 1.0 ~ 1.7976931348623157E308
		surfaceAreaTarget = 4.0
		#Amount of energy created (in heat) from each whole mB of fission fuel.
		energyPerFissionFuel = "1000000"

	#Hohlraum Settings
	[generators.hohlraum]
		#Amount of DT-Fuel Hohlraum can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 1
		#Hohlraum capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 10

