
[wirelessCraftingGrid]
	#The energy capacity of the Wireless Crafting Grid
	#Range: > 0
	capacity = 640000
	#The energy used by the Wireless Crafting Grid to open
	#Range: > 0
	openUsage = 1500
	#The energy used by the Wireless Crafting Grid to craft an item
	#Range: > 0
	craftUsage = 100
	#The energy used by the Wireless Crafting Grid to clear the crafting matrix
	#Range: > 0
	clearUsage = 900

