
[server]

	[server.server]

		[server.server.server]

			#mod.chiselsandbits.config.server.performance.comment
			[server.server.server.performance]

				[server.server.server.performance.server]

					[server.server.server.performance.server.performance]

						[server.server.server.performance.server.performance.memory]

							[server.server.server.performance.server.performance.memory.low-mode]
								#mod.chiselsandbits.config.server.performance.server.performance.memory.low-mode.enabled.comment
								enabled = false

		#mod.chiselsandbits.config.server.balancing.comment
		[server.server.balancing]

			[server.server.balancing.server]

				[server.server.balancing.server.balancing]
					#mod.chiselsandbits.config.server.balancing.server.balancing.wrench-uses.comment
					#Range: > -2147483648
					wrench-uses = 1888

					[server.server.balancing.server.balancing.random-ticking-blocks]
						#mod.chiselsandbits.config.server.balancing.server.balancing.random-ticking-blocks.blacklisted.comment
						blacklisted = false

					[server.server.balancing.server.balancing.tools]
						#mod.chiselsandbits.config.server.balancing.server.balancing.tools.damage.comment
						damage = true

						[server.server.balancing.server.balancing.tools.harvest-levels]
							#mod.chiselsandbits.config.server.balancing.server.balancing.tools.harvest-levels.enabled.comment
							enabled = true

					[server.server.balancing.server.balancing.chisel-tool]

						[server.server.balancing.server.balancing.chisel-tool.harvest-check]
							#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-tool.harvest-check.enabled.comment
							enabled = false
							#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-tool.harvest-check.tools.comment
							tools = ""

					[server.server.balancing.server.balancing.bits]
						#mod.chiselsandbits.config.server.balancing.server.balancing.bits.act-as-light-source.comment
						act-as-light-source = true
						#mod.chiselsandbits.config.server.balancing.server.balancing.bits.light-percentage.comment
						#Range: 4.9E-324 ~ 1.7976931348623157E308
						light-percentage = 6.25

					[server.server.balancing.server.balancing.compatibility-mode]
						#mod.chiselsandbits.config.server.balancing.server.balancing.compatibility-mode.enabled.comment
						enabled = false

					[server.server.balancing.server.balancing.bag]
						#mod.chiselsandbits.config.server.balancing.server.balancing.bag.stack-size.comment
						#Range: > -2147483648
						stack-size = 16384

					[server.server.balancing.server.balancing.chisel-uses]
						#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-uses.stone.comment
						#Range: > -2147483648
						stone = 12288
						#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-uses.iron.comment
						#Range: > -2147483648
						iron = 110592
						#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-uses.diamond.comment
						#Range: > -2147483648
						diamond = 995328
						#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-uses.netherite.comment
						#Range: > -2147483648
						netherite = 8957952
						#mod.chiselsandbits.config.server.balancing.server.balancing.chisel-uses.gold.comment
						#Range: > -2147483648
						gold = 1024

					[server.server.balancing.server.balancing.saw-uses]
						#mod.chiselsandbits.config.server.balancing.server.balancing.saw-uses.stone.comment
						#Range: > -2147483648
						stone = 512
						#mod.chiselsandbits.config.server.balancing.server.balancing.saw-uses.gold.comment
						#Range: > -2147483648
						gold = 500
						#mod.chiselsandbits.config.server.balancing.server.balancing.saw-uses.iron.comment
						#Range: > -2147483648
						iron = 2048
						#mod.chiselsandbits.config.server.balancing.server.balancing.saw-uses.diamond.comment
						#Range: > -2147483648
						diamond = 8192
						#mod.chiselsandbits.config.server.balancing.server.balancing.saw-uses.netherite.comment
						#Range: > -2147483648
						netherite = 32768

					[server.server.balancing.server.balancing.full-block-crafting]
						#mod.chiselsandbits.config.server.balancing.server.balancing.full-block-crafting.enabled.comment
						enabled = true

					[server.server.balancing.server.balancing.bag-space]
						#mod.chiselsandbits.config.server.balancing.server.balancing.bag-space.required.comment
						required = true
						#mod.chiselsandbits.config.server.balancing.server.balancing.bag-space.void-excess.comment
						void-excess = true

					[server.server.balancing.server.balancing.clipboard]

						[server.server.balancing.server.balancing.clipboard.size]
							#mod.chiselsandbits.config.server.balancing.server.balancing.clipboard.size.creative.comment
							#Range: > -2147483648
							creative = 10

					[server.server.balancing.server.balancing.revertible]
						#mod.chiselsandbits.config.server.balancing.server.balancing.revertible.blocks.comment
						blocks = ["*"]

	#mod.chiselsandbits.config.server.troubleshooting.comment
	[server.troubleshooting]

		[server.troubleshooting.server]

			[server.troubleshooting.server.troubleshooting]

				[server.troubleshooting.server.troubleshooting.logging]
					#mod.chiselsandbits.config.server.troubleshooting.server.troubleshooting.logging.tile-errors.comment
					tile-errors = true
					#mod.chiselsandbits.config.server.troubleshooting.server.troubleshooting.logging.eligibility-errors.comment
					eligibility-errors = true

