
#
#The Backbone of Create
[infrastructure]
	#
	#[in Ticks]
	#The amount of time a server waits before sending out tickrate synchronization packets.
	#These packets help animations to be more accurate when tps is below 20.
	#Range: > 5
	tickrateSyncTimer = 20

#
#Packmakers' control panel for internal recipe compat
[recipes]
	#
	#When true, allows any shapeless crafting recipes to be processed by a Mechanical Mixer + Basin.
	allowShapelessInMixer = true
	#
	#When true, allows any single-ingredient 2x2 or 3x3 crafting recipes to be processed by a Mechanical Press + Basin.
	allowShapedSquareInPress = true
	#
	#When true, allows any standard crafting recipes to be processed by Mechanical Crafters.
	allowRegularCraftingInCrafter = true
	#
	#When true, allows any stonecutting recipes to be processed by a Mechanical Saw.
	allowStonecuttingOnSaw = true
	#
	#The amount of Light sources destroyed before Chromatic Compound turns into Refined Radiance.
	#Range: > 1
	lightSourceCountForRefinedRadiance = 10
	#
	#Allow the standard in-world Refined Radiance recipes.
	enableRefinedRadianceRecipe = true
	#
	#Allow the standard in-world Shadow Steel recipe.
	enableShadowSteelRecipe = true

#
#Parameters and abilities of Create's kinetic mechanisms
[kinetics]
	#
	#Disable the Stress mechanic altogether.
	disableStress = false
	#
	#Maximum length in blocks of mechanical belts.
	#Range: > 5
	maxBeltLength = 20
	#
	#Damage dealt by active Crushing Wheels.
	#Range: > 0
	crushingDamage = 4
	#
	#[in Revolutions per Minute]
	#Maximum allowed speed of a configurable motor.
	#Range: > 64
	maxMotorSpeed = 256
	#
	#[in Revolutions per Minute]
	#Added rotation speed by a water wheel when at least one flow is present.
	#Range: > 1
	waterWheelBaseSpeed = 4
	#
	#[in Revolutions per Minute]
	#Rotation speed gained by a water wheel for each side with running fluids. (halved if not against blades)
	#Range: > 1
	waterWheelFlowSpeed = 4
	#
	#[in Revolutions per Minute]
	#Base rotation speed for the furnace engine generator
	#Range: > 1
	furnaceEngineSpeed = 16
	#
	#[in Revolutions per Minute]
	#Maximum allowed rotation speed for any Kinetic Tile.
	#Range: > 64
	maxRotationSpeed = 256
	#
	#Select what mobs should ignore Deployers when attacked by them.
	#Allowed Values: ALL, CREEPERS, NONE
	ignoreDeployerAttacks = "CREEPERS"
	#
	#Game ticks between Kinetic Blocks checking whether their source is still valid.
	#Range: > 5
	kineticValidationFrequency = 60
	#
	#multiplier used for calculating exhaustion from speed when a crank is turned.
	#Range: 0.0 ~ 1.0
	crankHungerMultiplier = 0.009999999776482582

	#
	#Encased Fan
	[kinetics.encasedFan]
		#
		#Maximum distance in blocks Fans can push entities.
		#Range: > 5
		fanPushDistance = 20
		#
		#Maximum distance in blocks from where Fans can pull entities.
		#Range: > 5
		fanPullDistance = 20
		#
		#Game ticks between Fans checking for anything blocking their air flow.
		#Range: > 10
		fanBlockCheckRate = 30
		#
		#[in Revolutions per Minute]
		#Rotation speed at which the maximum stats of fans are reached.
		#Range: > 64
		fanRotationArgmax = 256
		#
		#[in Revolutions per Minute]
		#Rotation speed generated by a vertical fan above fire.
		#Range: > 0
		generatingFanSpeed = 4
		#
		#Game ticks required for a Fan-based processing recipe to take effect.
		#Range: > 0
		inWorldProcessingTime = 150

	#
	#Moving Contraptions
	[kinetics.contraptions]
		#
		#Maximum amount of blocks in a structure movable by Pistons, Bearings or other means.
		#Range: > 1
		maxBlocksMoved = 2048
		#
		#Maximum value of a chassis attachment range.
		#Range: > 1
		maxChassisRange = 16
		#
		#Maximum amount of extension poles behind a Mechanical Piston.
		#Range: > 1
		maxPistonPoles = 64
		#
		#Max length of rope available off a Rope Pulley.
		#Range: > 1
		maxRopeLength = 128
		#
		#Maximum allowed distance of two coupled minecarts.
		#Range: > 1
		maxCartCouplingLength = 32

	[kinetics.stressValues]

		#
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v1]

			#
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v1.impact]
				deployer = 4.0
				mechanical_piston = 4.0
				millstone = 4.0
				mechanical_bearing = 4.0
				clockwork_bearing = 4.0
				cuckoo_clock = 1.0
				speedometer = 0.0
				mechanical_saw = 4.0
				flywheel = 0.0
				encased_chain_drive = 0.0
				clutch = 0.0
				encased_fan = 2.0
				adjustable_chain_gearshift = 0.0
				mechanical_pump = 4.0
				crushing_wheel = 8.0
				mechanical_mixer = 4.0
				rope_pulley = 4.0
				rotation_speed_controller = 0.0
				mechanical_arm = 8.0
				andesite_encased_shaft = 0.0
				mechanical_press = 8.0
				large_cogwheel = 0.0
				mechanical_drill = 4.0
				mysterious_cuckoo_clock = 1.0
				stressometer = 0.0
				shaft = 0.0
				brass_encased_shaft = 0.0
				gearshift = 0.0
				turntable = 4.0
				sticky_mechanical_piston = 4.0
				sequenced_gearshift = 0.0
				cogwheel = 0.0
				belt = 1.0
				gearbox = 0.0
				hose_pulley = 4.0
				mechanical_crafter = 2.0

			#
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v1.capacity]
				hand_crank = 8.0
				furnace_engine = 1024.0
				encased_fan = 16.0
				creative_motor = 16384.0
				water_wheel = 16.0
				windmill_bearing = 512.0

		#
		#Configure speed/capacity levels for requirements and indicators.
		[kinetics.stressValues.stats]
			#
			#[in Revolutions per Minute]
			#Minimum speed of rotation to be considered 'medium'
			#Range: 0.0 ~ 4096.0
			mediumSpeed = 30.0
			#
			#[in Revolutions per Minute]
			#Minimum speed of rotation to be considered 'fast'
			#Range: 0.0 ~ 65535.0
			fastSpeed = 100.0
			#
			#[in Stress Units]
			#Minimum stress impact to be considered 'medium'
			#Range: 0.0 ~ 4096.0
			mediumStressImpact = 4.0
			#
			#[in Stress Units]
			#Minimum stress impact to be considered 'high'
			#Range: 0.0 ~ 65535.0
			highStressImpact = 8.0
			#
			#[in Stress Units]
			#Minimum added Capacity by sources to be considered 'medium'
			#Range: 0.0 ~ 4096.0
			mediumCapacity = 128.0
			#
			#[in Stress Units]
			#Minimum added Capacity by sources to be considered 'high'
			#Range: 0.0 ~ 65535.0
			highCapacity = 512.0

#
#Create's liquid manipulation tools
[fluids]
	#
	#[in Buckets]
	#The amount of liquid a tank can hold per block.
	#Range: > 1
	fluidTankCapacity = 16
	#
	#[in Blocks]
	#The maximum height a fluid tank can reach.
	#Range: > 1
	fluidTankMaxHeight = 32
	#
	#[in Blocks]
	#The maximum distance a mechanical pump can push or pull liquids on either side.
	#Range: > 1
	mechanicalPumpRange = 16
	#
	#[in Blocks]
	#[-1 to disable this behaviour]
	#The minimum amount of fluid blocks the hose pulley needs to find before deeming it an infinite source.
	#Range: > -1
	hosePulleyBlockThreshold = 10000
	#
	#[in Blocks]
	#The maximum distance a hose pulley can draw fluid blocks from.
	#Range: > 1
	hosePulleyRange = 128

#
#Tweaks for logistical components
[logistics]
	#
	#The maximum amount of items a funnel pulls at a time without an applied filter.
	#Range: 1 ~ 64
	defaultExtractionLimit = 64
	#
	#The amount of ticks a funnel waits between item transferrals, when it is not re-activated by redstone.
	#Range: > 1
	defaultExtractionTimer = 8
	#
	#The amount of ticks a portable storage interface waits for transfers until letting contraptions move along.
	#Range: > 1
	psiTimeout = 20
	#
	#Maximum distance in blocks a Mechanical Arm can reach across.
	#Range: > 1
	mechanicalArmRange = 5
	#
	#Maximum possible range in blocks of redstone link connections.
	#Range: > 1
	linkRange = 128

#
#Everything related to Schematic tools
[schematics]
	#
	#[in KiloBytes]
	#The maximum allowed file size of uploaded Schematics.
	#Range: > 16
	maxSchematics = 256
	#
	#[in Bytes]
	#The maximum packet size uploaded Schematics are split into.
	#Range: 256 ~ 32767
	maxSchematicPacketSize = 1024
	#
	#Amount of game ticks without new packets arriving until an active schematic upload process is discarded.
	#Range: > 100
	schematicIdleTimeout = 600

	#
	#Schematicannon
	[schematics.schematicannon]
		#
		#Amount of game ticks between shots of the cannon. Higher => Slower
		#Range: > 1
		schematicannonDelay = 10
		#
		#Amount of block positions per tick scanned by a running cannon. Higher => Faster
		#Range: > 1
		schematicannonSkips = 10
		#
		#% of Schematicannon's Fuel filled by 1 Gunpowder.
		#Range: 0.0 ~ 100.0
		schematicannonGunpowderWorth = 20.0
		#
		#% of Schematicannon's Fuel used for each fired block.
		#Range: 0.0 ~ 100.0
		schematicannonFuelUsage = 0.05000000074505806

#
#Gadgets and other Shenanigans added by Create
[curiosities]
	#
	#The Maximum Distance to an active mirror for the symmetry wand to trigger.
	#Range: > 10
	maxSymmetryWandRange = 50

