#Disables fake players like miners and auto-clickers.
disable_fake_players = false
#Max claimed chunks.
#You can override this with FTB Ranks 'ftbchunks.max_claimed' permission
#Range: > 0
max_claimed_chunks = 500
#Max force loaded chunks.
#You can override this with FTB Ranks 'ftbchunks.max_force_loaded' permission
#Range: > 0
max_force_loaded_chunks = 10
#Disables all land protection. Useful for private servers where everyone is trusted and claims are only used for forceloading.
disable_protection = false
#Forced modes won't let players change their ally settings.
#Allowed Values: DEFAULT, FORCED_ALL, FORCED_NONE
ally_mode = "DEFAULT"
#Allow players to load chunks while they are offline.
chunk_load_offline = false
#Blacklist for dimensions where chunks can't be claimed.
claim_dimension_blacklist = ["minecraft:the_end"]
#Patches vanilla chunkloading to allow random block ticks and other environment updates in chunks where no players are nearby. With this off farms and other things won't work. Disable in case this causes issues.
patch_chunkloading = true

