#If this is set to true every living entity will generate a gravestone
enable_living_entity_graves = false
#If this is set to true you get a death note after you died
enable_death_note = true
#The blocks that can be replaced with a grave when someone dies there
replaceable_blocks = ["minecraft:tall_grass", "minecraft:grass", "minecraft:water", "minecraft:lava", "minecraft:dandelion", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:sunflower", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:azure_bluet", "minecraft:oxeye_daisy", "minecraft:orange_tulip", "minecraft:pink_tulip", "minecraft:red_tulip", "minecraft:white_tulip", "minecraft:allium", "minecraft:fern", "minecraft:large_fern", "minecraft:spruce_sapling", "minecraft:acacia_sapling", "minecraft:birch_sapling", "minecraft:dark_oak_sapling", "minecraft:jungle_sapling", "minecraft:oak_sapling", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:snow", "minecraft:vine", "minecraft:dead_bush", "minecraft:fire"]
#If this is set to true the death note will be taken out of your inventory when you destroyed the gravestone
remove_death_note = false
#If this is set to true only the player that owns the gravestone and the admins can break the gravestone
only_owners_can_break = false
#If this is set to true a ghost of the dead player will be spawned when the gravestone is broken
spawn_ghost = false
#If this is set to true the ghost of the dead player will defend him
friendly_ghost = true

