
[curse_breaking]
	enable = true

[curse_butterfingers]
	enable = true

[curse_aquaphobia]
	enable = true

[curse_death]
	enable = true

[reinforced_tip]
	enable = true

[stone_mending]
	enable = true

[lumberjack]
	enable = true

[momentum]
	enable = true

[butchering]
	enable = true

[true_shot]
	enable = false

[quick_draw]
	enable = true

[floating]
	enable = true

[paralysis]
	enable = true

[detonation]
	enable = true

[combo]
	enable = true

[faster_attack]
	enable = true

[lifesteal]
	enable = true

[ice_aspect]
	enable = true

[wisdom]
	enable = true

[blazing_walker]
	enable = true

[step_assist]
	enable = true

[night_vision]
	enable = true

[multi_jump]
	enable = true

[timeless]
	enable = true

