
[general]
	#How many times the tape roll can be used before it breaks
	#Range: 0 ~ 2147483646
	tape_roll_uses = 8
	#TileEntities to disallow (whitelist takes precedence)
	#NOTE: This list now uses 'Block Entity Type' IDs. Eg. the shulker boxes are 'minecraft:shulker_box'.
	blacklist = []
	#TileEntities to allow regardless of the blacklist and vanilla restrictions.
	#WARNING: This whitelist bypasses the 'only ops can copy' limitation of Minecraft, which can result in security issues, don't whitelist things unless you know what the side-effects will be.
	#NOTE: This list now uses 'Block Entity Type' IDs. Eg. the spawner is 'minecraft:mob_spawner'.
	whitelist = []
	#Whether the tape roll consumes paper when used
	consume_paper = true

