
[milestones]
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order.
	milestones = [25, 50, 100, 150, 200, 250, 300, 350, 400, 500]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10

[filtering]
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = ["farmersdelight:fried_egg", "environmental:cherry_pie", "environmental:apple_pie", "simplefarming:apple_pie", "simplefarming:blueberry_pie", "abnormals_delight:adzuki_cake_slice", "abnormals_delight:banana_cake_slice", "abnormals_delight:cherry_pantry", "abnormals_delight:chocolate_cake_slice", "abnormals_delight:cooked_duck_fillet", "abnormals_delight:cooked_venison_shanks", "abnormals_delight:duck_fillet", "abnormals_delight:mint_cake_slice", "abnormals_delight:necromium_knife", "abnormals_delight:passionfruit_glazed_duck", "abnormals_delight:seared_venison", "abnormals_delight:strawberry_cake_slice", "abnormals_delight:vanilla_cake_slice", "abnormals_delight:venison_shanks", "abnormals_delight:willow_pantry", "abnormals_delight:wisteria_pantry", "abnormals_delight:escargot", "abnormals_delight:maple_cookie", "abnormals_delight:maple_glazed_bacon", "aquaculture:frog_legs_cooked", "aquaculture:frog_legs_raw", "projectvibrantjourneys:clam", "projectvibrantjourneys:clam_chowder", "projectvibrantjourneys:cooked_clam", "simplefarming:chocolate", "simplefarming:cooked_bacon", "simplefarming:cooked_egg", "simplefarming:raw_bacon"]
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false

