
["Global Options"]
	#If TRUE, Thermal Blocks will retain Inventory Contents when dropped.
	"Blocks Retain Inventory" = false
	#If TRUE, Thermal Blocks will retain Redstone Control configuration when dropped.
	"Blocks Retain Redstone Control" = true
	#If TRUE, Thermal Blocks will retain Side configuration when dropped.
	"Blocks Retain Side Configuration" = true
	#If TRUE, Thermal Blocks will retain Transfer Control configuration when dropped.
	"Blocks Retain Transfer Control" = true
	#If TRUE, Thermal Blocks will retain Tank Contents when dropped.
	"Blocks Retain Tank Contents" = true
	#If TRUE, Thermal Blocks will retain Augments when dropped.
	"Blocks Retain Augments" = true
	#If TRUE, Thermal Blocks will retain Energy when dropped.
	"Blocks Retain Energy" = true

[Features]
	#If TRUE, various 'Vanilla+' Blocks and Recipes are enabled.
	"Vanilla+" = true
	#IF TRUE, the Blitz Mob is enabled.
	Blitz = true
	#IF TRUE, Rockwool Blocks and Recipes are enabled.
	Rockwool = true
	#IF TRUE, the Basalz Mob is enabled.
	Basalz = true
	#IF TRUE, the Blizz Mob is enabled.
	Blizz = true

["World Generation"]
	#Set to FALSE to prevent 'Thermal Series' Silver from generating.
	Silver = false
	#Set to FALSE to prevent 'Thermal Series' Cinnabar from generating.
	Cinnabar = false
	#Set to FALSE to prevent 'Thermal Series' Tin from generating.
	Tin = false
	#Set to FALSE to prevent 'Thermal Series' Lead from generating.
	Lead = false
	#Set to FALSE to prevent 'Thermal Series' Apatite from generating.
	Apatite = false
	#Set to FALSE to prevent 'Thermal Series' Niter from generating.
	Niter = false
	#Set to FALSE to prevent 'Thermal Series' Nickel from generating.
	Nickel = false
	#Set to FALSE to prevent 'Thermal Series' Sulfur from generating.
	Sulfur = false
	#Set to FALSE to prevent 'Thermal Series' Copper from generating.
	Copper = false

