
[travel-anchor-settings]
	#The maximum angle you can look at the Travel Anchor to teleport.
	#Be sure to write a .0 after a whole number because forges config system can not handle whole numbers without it.
	#Range: 1.0 ~ 1.7976931348623157E308
	maxAngle = 30.0
	#The maximum distance you are allowed to teleport.
	#Be sure to write a .0 after a whole number because forges config system can not handle whole numbers without it.
	#Range: 1.0 ~ 1.7976931348623157E308
	maxDistance = 64.0

