
#Common only settings for Abnormals Core, this will affect all depending mods
[common]
	#If Quark Sign Editing should be enabled; Default: True
	quarkSignEditing = true
	#If Quark Sign Editing requires an empty hand to edit; Default: False
	signEditingRequiresEmptyHand = false

	#Compatibility with Quark's poisonous potatoes feature
	[common.poisonousPotatoCompat]
		#If growth stunting should give a booflo poison; Default: True
		poisonEffect = true
		#The chance to stunt booflo growth when feeding a poisonous potato; Default: 0.1
		#Range: 0.0 ~ 1.0
		poisonChance = 0.1
		#If booflos can be fed a poisonous potato to stunt their growth when Quark is installed; Default: True
		poisonPotatoCompatEnabled = true

