
#Biome config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[biome_configs]
	grizzlyBear = ["&#overworld+|@forest+|#forest"]
	roadrunner = ["&#overworld+|@desert"]
	boneSerpent = ["|#nether"]
	gazelle = ["&#overworld+|@savanna+|#savanna"]
	crocodile = ["&#overworld+|#swamp+|#river+!#cold"]
	fly = ["&#overworld+!@ocean+!#ocean"]
	hummingbird = ["&#overworld+|minecraft:flower_forest+|minecraft:sunflower_plains+|#jungle"]
	orca = ["&#overworld+|#ocean+&#cold"]
	sunbird = ["&#overworld+|#mountain"]
	gorilla = ["&#overworld+|#jungle+!minecraft:bamboo_jungle+!minecraft:bamboo_jungle_hills"]
	crimsonMosquito = ["|minecraft:crimson_forest"]
	rattlesnake = ["&#overworld+|#mesa", "&#overworld+|@desert"]
	endergrade = ["&#end+!minecraft:the_end"]
	hammerheadShark = ["&#overworld+|#ocean+&#hot"]
	lobster = ["&#overworld+|#beach"]
	komodoDragon = ["&#overworld+|#mesa"]
	capuchinMonkey = ["&#overworld+|#jungle+!minecraft:bamboo_jungle+!minecraft:bamboo_jungle_hills"]
	caveCentipede = ["&#overworld+!#ocean+!#mushroom"]
	warpedToad = ["|minecraft:warped_forest"]
	moose = ["&#overworld+|#snowy+&#wasteland", "&#overworld+|#snowy+&#forest"]
	mimicube = ["&#end+!minecraft:the_end"]
	raccoon = ["&#overworld+!#savanna+!#@savanna+|@forest+|#forest+|@plains+|#plains"]
	blobfish = ["&#overworld+|minecraft:deep_ocean+|minecraft:deep_cold_ocean+|minecraft:deep_frozen_ocean+|minecraft:deep_lukewarm_ocean"]
	seal = ["&#overworld+|#beach+", "&#overworld+|#ocean+&#snowy"]
	cockroach = ["&#overworld+!#ocean+!#mushroom"]
	shoebill = ["&#overworld+|#swamp+"]
	elephant = ["&#overworld+|@savanna+|#savanna"]
	soulVulture = ["|minecraft:soul_sand_valley"]
	snowLeopard = ["&#overworld+|#snowy+&#mountain"]
	spectre = ["|minecraft:small_end_islands"]
	crow = ["&#overworld+!#savanna+!#@savanna+|@forest+|#forest+|@plains+|#plains"]

