
[general]
	#Whether all players should get an Animal Dictionary when joining the world for the first time.
	giveBookOnStartup = false
	#Lava Opacity for the Lava Vision Potion.
	#Range: 0.01 ~ 1.0
	lavaVisionOpacity = 0.65
	#Whether bananas should drop from blocks tagged with #alexsmobs:drops_bananas
	bananasDropFromLeaves = true
	#1 out of this number chance for leaves to drop a banana when broken. Fortune is automatically factored in
	#Range: > 0
	bananaChance = 200
	#Whether spiders should target fly mobs.
	spidersAttackFlies = true
	#Whether wolves should target moose mobs.
	wolvesAttackMoose = true
	#Whether lava can be bottled with a right click of a glass bottle.
	lavaBottleEnabled = true
	#Maximum world y-level that cave centipedes can spawn at
	#Range: 0 ~ 256
	caveCentipedeSpawnHeight = 30
	#Whether to disable certain aspects of the Lava Vision Potion. Enable if issues with shaders persist.
	shadersCompat = false
	#Maximum world y-level that blobfish can spawn at
	#Range: 0 ~ 256
	blobfishSpawnHeight = 38
	#Whether mimicubes spawns should be restricted solely to the end city structure or to whatever biome is specified in their respective biome config.
	mimicubeSpawnInEndCity = true
	#Whether mimicream can be used to duplicate items.
	mimicreamRepair = true
	#Blacklist for items that mimicream cannot make a copy of. Ex: "minecraft:stone_sword", "alexsmobs:blood_sprayer"
	mimicreamBlacklist = ["alexsmobs:blood_sprayer"]
	#Whether wild raccoons steal food from chests.
	raccoonStealFromChests = true
	#Whether polar bears should target seal mobs.
	polarBearsAttackSeals = true
	#Whether soul vulture spawns should be restricted solely to the nether fossil structure or to whatever biome is specified in their respective biome config.
	soulVultureSpawnOnFossil = true
	#Whether acacia blossoms should drop from blocks tagged with #alexsmobs:drops_acacia_blossoms
	acaciaBlossomsDropFromLeaves = true
	#Whether bone serpents are neutral or hostile.
	neutralBoneSerpents = false
	#Whether fish oil gives players a special levitation effect.
	fishOilMeme = true
	#Whether wandering traders offer items like acacia blossoms, mosquito larva, crocodile egg, etc.
	wanderingTraderOffers = true
	#0 = no mungus biome transformation. 1 = mungus changes blocks, but not chunk's biome. 2 = mungus transforms blocks and biome of chunk.
	#Range: 0 ~ 2
	mungusBiomeTransformationType = 2
	#List of all mungus mushrooms, biome transformations and surface blocks. Each is seperated by a |. Add an entry with a block registry name, biome registry name, and block registry name(for the ground).
	mungusBiomeMatches = ["minecraft:red_mushroom|minecraft:mushroom_fields|minecraft:mycelium", "minecraft:brown_mushroom|minecraft:mushroom_fields|minecraft:mycelium", "minecraft:crimson_fungus|minecraft:crimson_forest|minecraft:crimson_nylium", "minecraft:warped_fungus|minecraft:warped_forest|minecraft:warped_nylium"]
	#Whether guster spawns are limited to when it is raining/thundering.
	limitGusterSpawnsToWeather = true
	#Whether Crimson Mosquitoes can transform into Warped Moscos if attacking a Mungus or any listed creature.
	warpedMoscoTransformation = true
	#List of extra(non mungus) mobs that will trigger a crimson mosquito to become a warped mosquito. Ex: "minecraft:mooshroom", "alexsmobs:warped_toad"
	warpedMoscoMobTriggers = [""]
	#True if straddleboard enchants are enabled.
	straddleboardEnchants = true
	#Whether emu should target skeletons.
	emuTargetSkeletons = true
	#Percent chance for emu leggings to dodge projectile attacks.
	#Range: 0.0 ~ 1.0
	emuPantsDodgeChance = 0.45

	[general.spawning]
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		grizzlyBearSpawnWeight = 8
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		grizzlyBearSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		roadrunnerSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		roadrunnerSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		boneSerpentSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		boneSeprentSpawnRolls = 50
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gazelleSpawnWeight = 40
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gazelleSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crocodileSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crocSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		flySpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		flySpawnRolls = 2
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hummingbirdSpawnWeight = 39
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hummingbirdSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		orcaSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		orcaSpawnRolls = 50
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sunbirdSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sunbirdSpawnRolls = 15
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gorillaSpawnWeight = 50
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gorillaSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crimsonMosquitoSpawnWeight = 11
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crimsonMosquitoSpawnRolls = 20
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		rattlesnakeSpawnWeight = 3
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		rattlesnakeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		endergradeSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		endergradeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hammerheadSharkSpawnWeight = 8
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hammerheadSharkSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		lobsterSpawnWeight = 7
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		lobsterSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		komodoDragonSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		komodoDragonSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		capuchinMonkeySpawnWeight = 55
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		capuchinMonkeySpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		caveCentipedeSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		caveCentipedeSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		warpedToadSpawnWeight = 80
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		warpedToadSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mooseSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mooseSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mimicubeSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mimicubeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		raccoonSpawnWeight = 3
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		raccoonSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		blobfishSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		blobfishSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sealSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sealSpawnRolls = 10
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		cockroachSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		cockroachSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		shoebillSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		shoebillSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		elephantSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		elephantSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		soulVultureSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		soulVultureSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		snowLeopardSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		snowLeopardSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		spectreSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		spectreSpawnRolls = 5
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crowSpawnWeight = 3
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crowSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		alligatorSnappingTurtleSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		alligatorSnappingTurtleSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mungusSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mungusSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mantisShrimpSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mantisShrimpSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gusterSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gusterSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn. NOTE: By default the warped mosco doesn't spawn in any biomes.
		#Range: 0 ~ 1000
		warpedMoscoSpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		warpedMoscoSpawnRolls = 1000
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		straddlerSpawnWeight = 8
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		straddlerSpawnRolls = 15
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		stradpoleSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		stradpoleSpawnRolls = 3
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		emuSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		emuSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		platypusSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		platypusSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		dropbearSpawnWeight = 19
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		dropbearSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		tasmanianDevilSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		tasmanianDevilSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		kangarooSpawnWeight = 25
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		kangarooSpawnRolls = 0

