
#General settings
[general]
	#How often Sylphs spawn
	#Range: 0 ~ 100
	sylphWeight = 5
	#Spawn Arcane Ore in the world
	genOre = false
	#Spawn a book in the players inventory on login
	spawnBook = false
	#Spawn Mana Berry Bushes in the world
	genBerries = true
	#How often Carbuncles spawn
	#Range: 0 ~ 100
	carbuncleWeight = 5
	#Rate of tree spawn per chunk
	#Range: 0.0 ~ 1.0
	genTrees = 0.002

#Enabled Spells
[spells]
	#Intangible enabled?
	intangible = true
	#Flare enabled?
	flare = true
	#Ignite enabled?
	ignite = true
	#Strength enabled?
	strength = true
	#Craft enabled?
	craft = true
	#Cold Snap enabled?
	cold_snap = true
	#Rune enabled?
	rune = true
	#Snare enabled?
	snare = true
	#Slowfall enabled?
	slowfall = true
	#Freeze enabled?
	freeze = true
	#Split enabled?
	split = true
	#Smelt enabled?
	smelt = true
	#Accelerate enabled?
	accelerate = true
	#Summon Vex enabled?
	summon_vex = true
	#Lightning enabled?
	lightning = true
	#Grow enabled?
	grow = true
	#Dampen enabled?
	dampen = true
	#Touch enabled?
	touch = true
	#Invisibility enabled?
	invisibility = true
	#Delay enabled?
	delay = true
	#Extract enabled?
	extract = true
	#Light enabled?
	light = true
	#Duration Down enabled?
	duration_down = true
	#Exchange enabled?
	exchange = true
	#Place Block enabled?
	place_block = true
	#Shield enabled?
	shield = true
	#Conjure Water enabled?
	conjure_water = true
	#Harm enabled?
	harm = true
	#Interact enabled?
	interact = true
	#Blink enabled?
	blink = true
	#Amplify enabled?
	amplify = true
	#Phantom enabled?
	phantom_block = true
	#Extend Time enabled?
	extend_time = true
	#Heal enabled?
	heal = true
	#Leap enabled?
	leap = true
	#Redstone Signal enabled?
	redstone_signal = true
	#Pierce enabled?
	pierce = true
	#Harvest enabled?
	harvest = true
	#Fortune enabled?
	fortune = true
	#Break enabled?
	break = true
	#Item Pickup enabled?
	pickup = true
	#Launch enabled?
	launch = true
	#Dispel enabled?
	dispel = true
	#Speed enabled?
	haste = true
	#Access Ender Inventory enabled?
	ender_inventory = true
	#Pull enabled?
	pull = true
	#Explosion enabled?
	explosion = true
	#Fangs enabled?
	fangs = true
	#AOE enabled?
	aoe = true
	#Gravity enabled?
	gravity = true
	#Self enabled?
	self = true
	#Aquatic enabled?
	aquatic = true
	#Projectile enabled?
	projectile = true
	#Wither enabled?
	wither = true
	#Knockback enabled?
	gust = true
	#Crush enabled?
	crush = true
	#Cut enabled?
	cut = true
	#Fell enabled?
	fell = true
	#Summon Steed enabled?
	summon_steed = true
	#Summon Wolves enabled?
	summon_wolves = true

#Mana
[mana]
	#Base mana regen in seconds
	#Range: > 0
	baseRegen = 5
	#Max mana bonus for tier of book
	#Range: > 0
	tierMax = 50
	#How often max and regen will be calculated, in ticks. NOTE: Having the base mana regen AT LEAST this value is recommended.
	#Range: 1 ~ 20
	updateInterval = 5
	#Mana Boost value per level
	#Range: > 0
	manaBoost = 25
	#Regen bonus per potion level
	#Range: > 0
	potionRegen = 10
	#Max mana bonus per glyph
	#Range: > 0
	glyphmax = 15
	#(enchantment) Mana regen per second per level
	#Range: > 0
	manaRegenEnchantment = 2
	#Base max mana
	#Range: > 0
	baseMax = 100
	#Regen bonus per glyph
	#Range: 0.0 ~ 2.147483647E9
	glyphRegen = 0.33

#Spell Cost
[spell_cost]
	#Speed cost
	#Range: > -2147483648
	haste_cost = 30
	#Summon Vex cost
	#Range: > -2147483648
	summon_vex_cost = 75
	#Dampen cost
	#Range: > -2147483648
	dampen_cost = -5
	#Knockback cost
	#Range: > -2147483648
	gust_cost = 15
	#Touch cost
	#Range: > -2147483648
	touch_cost = 5
	#Extract cost
	#Range: > -2147483648
	extract_cost = 30
	#Aquatic cost
	#Range: > -2147483648
	aquatic_cost = 25
	#Smelt cost
	#Range: > -2147483648
	smelt_cost = 100
	#Blink cost
	#Range: > -2147483648
	blink_cost = 50
	#Launch cost
	#Range: > -2147483648
	launch_cost = 30
	#Intangible cost
	#Range: > -2147483648
	intangible_cost = 30
	#Rune cost
	#Range: > -2147483648
	rune_cost = 30
	#Flare cost
	#Range: > -2147483648
	flare_cost = 40
	#Break cost
	#Range: > -2147483648
	break_cost = 10
	#Pull cost
	#Range: > -2147483648
	pull_cost = 15
	#Wither cost
	#Range: > -2147483648
	wither_cost = 50
	#Extend Time cost
	#Range: > -2147483648
	extend_time_cost = 10
	#Snare cost
	#Range: > -2147483648
	snare_cost = 80
	#Item Pickup cost
	#Range: > -2147483648
	pickup_cost = 10
	#Explosion cost
	#Range: > -2147483648
	explosion_cost = 35
	#Slowfall cost
	#Range: > -2147483648
	slowfall_cost = 25
	#Harm cost
	#Range: > -2147483648
	harm_cost = 15
	#Exchange cost
	#Range: > -2147483648
	exchange_cost = 50
	#Leap cost
	#Range: > -2147483648
	leap_cost = 20
	#Dispel cost
	#Range: > -2147483648
	dispel_cost = 30
	#Craft cost
	#Range: > -2147483648
	craft_cost = 50
	#Place Block cost
	#Range: > -2147483648
	place_block_cost = 10
	#Delay cost
	#Range: > -2147483648
	delay_cost = 50
	#Shield cost
	#Range: > -2147483648
	shield_cost = 30
	#Fortune cost
	#Range: > -2147483648
	fortune_cost = 80
	#Self cost
	#Range: > -2147483648
	self_cost = 10
	#Ignite cost
	#Range: > -2147483648
	ignite_cost = 15
	#Freeze cost
	#Range: > -2147483648
	freeze_cost = 15
	#Heal cost
	#Range: > -2147483648
	heal_cost = 40
	#Harvest cost
	#Range: > -2147483648
	harvest_cost = 30
	#Access Ender Inventory cost
	#Range: > -2147483648
	ender_inventory_cost = 50
	#Pierce cost
	#Range: > -2147483648
	pierce_cost = 20
	#Invisibility cost
	#Range: > -2147483648
	invisibility_cost = 30
	#Gravity cost
	#Range: > -2147483648
	gravity_cost = 15
	#Duration Down cost
	#Range: > -2147483648
	duration_down_cost = 15
	#Light cost
	#Range: > -2147483648
	light_cost = 25
	#Projectile cost
	#Range: > -2147483648
	projectile_cost = 10
	#Split cost
	#Range: > -2147483648
	split_cost = 20
	#Grow cost
	#Range: > -2147483648
	grow_cost = 70
	#Cold Snap cost
	#Range: > -2147483648
	cold_snap_cost = 30
	#Strength cost
	#Range: > -2147483648
	strength_cost = 0
	#Interact cost
	#Range: > -2147483648
	interact_cost = 10
	#Phantom cost
	#Range: > -2147483648
	phantom_block_cost = 5
	#Redstone Signal cost
	#Range: > -2147483648
	redstone_signal_cost = 0
	#Accelerate cost
	#Range: > -2147483648
	accelerate_cost = 10
	#Conjure Water cost
	#Range: > -2147483648
	conjure_water_cost = 80
	#Amplify cost
	#Range: > -2147483648
	amplify_cost = 20
	#Lightning cost
	#Range: > -2147483648
	lightning_cost = 50
	#Fangs cost
	#Range: > -2147483648
	fangs_cost = 35
	#AOE cost
	#Range: > -2147483648
	aoe_cost = 35
	#Crush cost
	#Range: > -2147483648
	crush_cost = 30
	#Cut cost
	#Range: > -2147483648
	cut_cost = 0
	#Fell cost
	#Range: > -2147483648
	fell_cost = 150
	#Summon Steed cost
	#Range: > -2147483648
	summon_steed_cost = 0
	#Summon Wolves cost
	#Range: > -2147483648
	summon_wolves_cost = 0

#Starting Spells
["Starter Spells"]
	projectile_starter = true
	touch_starter = true
	self_starter = true
	break_starter = true
	harm_starter = true

