
[campsite]
	#Chance for an ore vein to generate underneath a campsite
	#Range: 0.0 ~ 1.0
	campsite_ore_chance = 0.25
	#The minimum y-level at which a campsite can generate
	#Range: 0 ~ 255
	campsite_min_y = 0
	#The maximum y-level at which a campsite can generate
	#Range: 0 ~ 255
	campsite_max_y = 45
	#Chance for a container of a campsite to be replaced by a mimic
	#Range: 0.0 ~ 1.0
	campsite_mimic_chance = 0.2
	#Per-chunk chance a campsite is attempted to be generated. Not every attempt succeeds, this also depends on the density and shape of caves
	#Range: 0.0 ~ 1.0
	campsite_chance = 0.2

