
#To disable items or to change the frequency at which artifacts appear, override the loot tables from this mod with a datapack
#Cosmetic slots are disabled by default, they can be enabled using the Curios config, see https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users#creating-a-new-slot-type
[campsite]
	#Probability for an ore vein to generate underneath a campsite
	#Range: 0 ~ 100
	campsite_ore_chance = 25
	#The minimum y-level at which a campsite can generate
	#Range: 1 ~ 255
	campsite_min_y = 1
	#The maximum y-level at which a campsite can generate
	#Range: 0 ~ 255
	campsite_max_y = 45
	#Whether to use wooden chests from other mods when generating campsites, may make it easier to distinguish them from mimics
	use_modded_chests = false
	#Probability for a container of a campsite to be replaced by a mimic
	#Range: 0 ~ 100
	campsite_mimic_chance = 30
	#List of biome IDs in which campsites are not allowed to generate. End and nether biomes are excluded by default.
	# To blacklist all biomes from a single mod, use 'modid:*'
	biome_blacklist = ["minecraft:void", "undergarden:*"]
	#Per-chunk probability (as a percentage) a campsite is attempted to be generated. Not every attempt succeeds, this also depends on the density and shape of caves
	#Range: 0 ~ 100
	campsite_chance = 8

[items]
	#Cooldown in ticks for the Everlasting Beef and Eternal Steak items
	#Range: > 0
	eternal_food_cooldown = 300

