
[worldgen]

	[worldgen.small_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["forest", "plains"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.glow_flower]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.marble]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = []
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = true
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.desert_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["mesa", "desert", "savanna"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.aquamarine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.ancient_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.rock_crystal]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

