
#Values for the minecraft:generic.max_health attribute.
[minecraft_generic_max_health]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 1.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.follow_range attribute.
[minecraft_generic_follow_range]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.knockback_resistance attribute.
[minecraft_generic_knockback_resistance]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.movement_speed attribute.
[minecraft_generic_movement_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.flying_speed attribute.
[minecraft_generic_flying_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.attack_damage attribute.
[minecraft_generic_attack_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.attack_knockback attribute.
[minecraft_generic_attack_knockback]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.attack_speed attribute.
[minecraft_generic_attack_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.armor attribute.
[minecraft_generic_armor]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.armor_toughness attribute.
[minecraft_generic_armor_toughness]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:generic.luck attribute.
[minecraft_generic_luck]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = -1024.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:zombie.spawn_reinforcements attribute.
[minecraft_zombie_spawn_reinforcements]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the minecraft:horse.jump_strength attribute.
[minecraft_horse_jump_strength]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:draw_speed attribute.
[apotheosis_draw_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:snipe_damage attribute.
[apotheosis_snipe_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:fire_damage attribute.
[apotheosis_fire_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:cold_damage attribute.
[apotheosis_cold_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:life_steal attribute.
[apotheosis_life_steal]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:piercing_damage attribute.
[apotheosis_piercing_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:current_hp_damage attribute.
[apotheosis_current_hp_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:crit_chance attribute.
[apotheosis_crit_chance]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:crit_damage attribute.
[apotheosis_crit_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the apotheosis:overhealing attribute.
[apotheosis_overhealing]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the tetra:draw_strength attribute.
[tetra_draw_strength]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the tetra:draw_speed attribute.
[tetra_draw_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the tetra:ability_cooldown attribute.
[tetra_ability_cooldown]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the tetra:ability_damage attribute.
[tetra_ability_damage]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the botania:pixie_spawn_chance attribute.
[botania_pixie_spawn_chance]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the caelus:elytra_flight attribute.
[caelus_elytra_flight]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the forge:swim_speed attribute.
[forge_swim_speed]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the forge:nametag_distance attribute.
[forge_nametag_distance]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 3.4028234663852886E38

#Values for the forge:entity_gravity attribute.
[forge_entity_gravity]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = -8.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

#Values for the forge:reach_distance attribute.
[forge_reach_distance]
	#Whether or not this attribute should be modified.
	enabled = true
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	min = 0.0
	#The maximum value for the attribute.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	max = 65536.0

