
#Values for the minecraft:generic.max_health attribute.
[minecraft_generic_max_health]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 1.0
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.follow_range attribute.
[minecraft_generic_follow_range]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.knockback_resistance attribute.
[minecraft_generic_knockback_resistance]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.movement_speed attribute.
[minecraft_generic_movement_speed]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.flying_speed attribute.
[minecraft_generic_flying_speed]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.attack_damage attribute.
[minecraft_generic_attack_damage]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.attack_knockback attribute.
[minecraft_generic_attack_knockback]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.attack_speed attribute.
[minecraft_generic_attack_speed]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.armor attribute.
[minecraft_generic_armor]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.armor_toughness attribute.
[minecraft_generic_armor_toughness]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:generic.luck attribute.
[minecraft_generic_luck]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:zombie.spawn_reinforcements attribute.
[minecraft_zombie_spawn_reinforcements]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

#Values for the minecraft:horse.jump_strength attribute.
[minecraft_horse_jump_strength]
	#The minimum vallue for the attribute. Changing this may have unforseen consequences.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min = 4.9E-324
	#The maximum value for the attribute.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max = 65536.0
	#Whether or not this attribute should be modified.
	enabled = true

