
#These options affect only the client that loads the mod.
[clientOnly]
	#Disabled tools, by their resource name. Eg: minecraft:diamond_hoe
	disabledTools = []
	#Some nbt tags will cause back tools to appear improperly. Use this setting to cleanse the item tags.
	nbtCleaner = ["Damage", "Charged", "ChargedProjectiles"]
	#Tool orientation, by class file and degrees. Separate with ":" . See defaults for examples.
	toolOrientation = ["net.minecraft.item.ToolItem:180", "net.minecraft.item.HoeItem:180", "net.minecraft.item.FishingRodItem:180", "net.minecraft.item.TridentItem:180", "net.minecraft.item.ShootableItem:90"]

