
#General settings for the mod.
[general]
	remove-bad-effects = true
	remove-positive-effects = true
	restore-health = true
	#Range: 0.0 ~ 1.7976931348623157E308
	restore-health-amount = 10.0

