#
# When loading files from datapacks, set this to true to log missing registry data for things like items.
# Default: false
log_missing_registry_data_for_datapacks = false
#
# The emerald cost for the Zeal Lighter sold by the Gatekeeper.
# Default: 12
gatekeeper_emerald_count = 8
#
# A list of mods that are allowed to generate features in our dimensions.
# Default: []
# Example: ["minecraft", "blue_skies", "botania"]
allowed_mods_for_feature_gen = []

