
#The general configuration for this mod
[general]
	#If this is set to true the Timeless Ivy will be added to the game.
	#Default: true
	enableTimelessIvy = true
	#If this is set to true the Terra Bow will be added to the game.
	#Default: true
	enableTerraBow = true
	#If this is set to true the Terra Harvester will be added to the game.
	#Default: true
	enableTerraHarvester = true

