
#Client side configurations for the mod. Modpacks should not ship non-default versions of this file!
[client]
	#Whether or not crops should render in pots.
	renderCrop = true
	#Whether or not the growth animation should be played.
	useGrowthAnimation = true
	#Whether or not the soil in pots should be rendered.
	renderSoil = true

