
#Client side configurations for the mod. Modpacks should not ship non-default versions of this file!
[client]
	#Whether or not crops should render in pots.
	renderCrop = true
	#Whether or not break effects should occur when harvested.
	breakEffects = true
	#Whether or not the growth animation should be played.
	useGrowthAnimation = true
	#Whether or not the soil in pots should be rendered.
	renderSoil = true
	#The render distance of a botany pot.
	#Range: 1.0 ~ 4096.0
	renderDistance = 64.0

