
#General mod settings
[general]
	#Determines if the Copy/Paste GUI's coordinate mode starts in 'Absolute' mode by default.
	#Set to true for Absolute, set to False for Relative.
	"Default to absolute Coord-Mode" = false

