
[General]
	#Silence the server-wide Wither spawn broadcast sound.
	silenceWither = true
	#Silence the server messages in console for when any of these sounds have been silenced.
	silenceSuccess = true
	#Silence the server-wide Ender Dragon Death broadcast sound.
	silenceDragon = true
	#Silence the server-wide Thunder broadcast sound caused by the Lightning event
	silenceLightning = true
	#A list of sounds to silence, discoverable with the toggle command /listen 
	#enter one sound event per line with no commas.
	silenceUs = []

