
#Mail configuration settings
[mail]
	#The maximum amount of mail that can be in a player's mail queue.
	#Range: > 1
	maxMailQueue = 50
	#The interval in ticks for mail boxes to pull mail from the player's queue
	#Range: > 1
	pullMailInterval = 20

