
[common]

	#mod.chiselsandbits.config.common.help.comment
	[common.help]

		[common.help.common]

			[common.help.common.help]
				#mod.chiselsandbits.config.common.help.common.help.enabled.comment
				enabled = true

	[common.common]

		#mod.chiselsandbits.config.common.performance.comment
		[common.common.performance]

			[common.common.performance.common]

				[common.common.performance.common.performance]

					[common.common.performance.common.performance.collisions]

						[common.common.performance.common.performance.collisions.cache]
							#mod.chiselsandbits.config.common.performance.common.performance.collisions.cache.size.comment
							#Range: -9223372036854775808 ~ 9223372036854775807
							size = 10000

