
["Config category"]
	#By default vanilla only displays advancements in chat which get broadcasted to all online players,this setting turns on showing all advancements achieved in chat instead. That way you can findthe advancements you got easier/see better which you get. Some of these may have no actual text though because the advancement itself doesnt have any, e.g. Categories are advancements too. default = true
	showAllInLocalChat = false

