
[Tooltips]
	#If TRUE, Item descriptions will be added to their tooltips if possible.
	"Show Item Descriptions" = true
	#If TRUE, Enchantment descriptions will be added to the tooltip for Enchanted Books containing only a single enchantment.
	"Show Enchantment Descriptions" = true
	#If TRUE and Advanced Tooltips are enabled (F3+H), Tags will be will be added to item tooltips if possible.
	"Show Item Tags" = false
	#If TRUE, CoFH Items will always show full details (charge state, etc.) and will not require Shift to be held down.
	"Always Show Item Details" = false
	#If TRUE, CoFH Items will display a message prompting to hold Shift to see full details (charge state, etc.). This does not change the behavior, only if the informational message should display.
	"Show 'Hold Shift for Details' Message" = true

