
[Collective]
	#When enabled, transfer the held items and armour from replaced entities by any of the Entity Spawn mods which depend on Collective.
	transferItemsBetweenReplacedEntities = true
	#The amount of times Collective loops through possible mob drops to get them all procedurally. Drops are only generated when a dependent mod uses them. Lowering this can increase world load time but decrease accuracy.
	#Range: 1 ~ 500
	loopsAmountUsedToGetAllEntityDrops = 100
	#The delay of the is-there-a-block-around-check around entities in ms. Used in mods which depends on a specific blockstate in the world. Increasing this number can increase TPS if needed.
	#Range: 0 ~ 3600000
	findABlockcheckAroundEntitiesDelayMs = 30000
	#Please check out https://stopmodreposts.org/ for more information on why this feature exists.
	enableAntiRepostingCheck = true
	#Enables pets for Patrons. Will be added in a future release.
	enablePatronPets = true

