
[worldgen]

	#
	#Modify Create's impact on your terrain
	[worldgen.v2]
		#
		#Prevents all worldgen added by Create from taking effect
		disableWorldGen = true
		#
		#Forward caught TileEntityExceptions to the log at debug level.
		logTeErrors = false

		[worldgen.v2.copper_ore]
			#No comment
			#Range: > 0
			clusterSize = 18
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 40
			#No comment
			#Range: > 0
			maxHeight = 85

		[worldgen.v2.weathered_limestone]
			#No comment
			#Range: > 0
			clusterSize = 128
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 10
			#No comment
			#Range: > 0
			maxHeight = 30

		[worldgen.v2.zinc_ore]
			#No comment
			#Range: > 0
			clusterSize = 14
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 15
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v2.limestone]
			#No comment
			#Range: > 0
			clusterSize = 128
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 30
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v2.dolomite]
			#No comment
			#Range: > 0
			clusterSize = 128
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 20
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v2.gabbro]
			#No comment
			#Range: > 0
			clusterSize = 128
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 20
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v2.scoria]
			#No comment
			#Range: > 0
			clusterSize = 128
			#
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0
			#No comment
			#Range: > 0
			minHeight = 0
			#No comment
			#Range: > 0
			maxHeight = 10

