
[worldgen]

	#
	#Modify Create's impact on your terrain
	[worldgen.v1]
		#
		#Prevents all worldgen added by Create from taking effect
		disableWorldGen = false
		#
		#Forward caught TileEntityExceptions to the log at debug level.
		logTeErrors = false

		[worldgen.v1.copper_ore]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 18
			#No comment
			#Range: > 0
			clusterCount = 2
			#No comment
			#Range: > 0
			minHeight = 40
			#No comment
			#Range: > 0
			maxHeight = 86

		[worldgen.v1.copper_ore_ocean]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 15
			#No comment
			#Range: > 0
			clusterCount = 4
			#No comment
			#Range: > 0
			minHeight = 20
			#No comment
			#Range: > 0
			maxHeight = 55

		[worldgen.v1.zinc_ore]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 14
			#No comment
			#Range: > 0
			clusterCount = 4
			#No comment
			#Range: > 0
			minHeight = 15
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v1.zinc_ore_desert]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 17
			#No comment
			#Range: > 0
			clusterCount = 5
			#No comment
			#Range: > 0
			minHeight = 10
			#No comment
			#Range: > 0
			maxHeight = 85

		[worldgen.v1.limestone]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 256
			#No comment
			#Range: 0.0 ~ 1.0
			clusterChance = 0.05
			#No comment
			#Range: > 0
			minHeight = 30
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v1.weathered_limestone]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 256
			#No comment
			#Range: 0.0 ~ 1.0
			clusterChance = 0.05
			#No comment
			#Range: > 0
			minHeight = 10
			#No comment
			#Range: > 0
			maxHeight = 30

		[worldgen.v1.dolomite]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 256
			#No comment
			#Range: 0.0 ~ 1.0
			clusterChance = 0.05
			#No comment
			#Range: > 0
			minHeight = 20
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v1.gabbro]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 256
			#No comment
			#Range: 0.0 ~ 1.0
			clusterChance = 0.05
			#No comment
			#Range: > 0
			minHeight = 20
			#No comment
			#Range: > 0
			maxHeight = 70

		[worldgen.v1.scoria]
			#
			#Whether to spawn this in your World
			enable = false
			#No comment
			#Range: > 0
			clusterSize = 256
			#No comment
			#Range: 0.0 ~ 1.0
			clusterChance = 0.05
			#No comment
			#Range: > 0
			minHeight = 0
			#No comment
			#Range: > 0
			maxHeight = 10

