#X position of dank hud element
#Range: > -2147483648
hudX = -150
#Y position of dank hud element
#Range: > -2147483648
hudY = -25

[client]
	#Whether to display the preview of the item in the dank, disable if you have optifine
	preview = true

