
#Decorative Blocks Configs
[general]
	#Bonfire Activator (define a resource location
	"bonfire activator" = "minecraft:blaze_powder"
	#Disable thatch creation on shearing hay bale
	"thatch enabled" = true

