
#World Gen - Ore Generation Configuration
["Ore Config: coal"]
	#Maximum Y-Level [Range: 0-256, Default: 128]
	#Range: 0 ~ 256
	max_y = 128
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 17]
	#Range: 0 ~ 64
	vein_size = 17
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: iron"]
	#Maximum Y-Level [Range: 0-256, Default: 64]
	#Range: 0 ~ 256
	max_y = 64
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 9]
	#Range: 0 ~ 64
	vein_size = 9
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: gold"]
	#Maximum Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	max_y = 32
	#Average ores per Chunk [Range: 0-64, Default: 2]
	#Range: 0 ~ 64
	count = 2
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 9]
	#Range: 0 ~ 64
	vein_size = 9
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: diamond"]
	#Maximum Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	max_y = 16
	#Average ores per Chunk [Range: 0-64, Default: 1]
	#Range: 0 ~ 64
	count = 1
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: emerald"]
	#Maximum Y-Level [Range: 0-256, Default: 128]
	#Range: 0 ~ 256
	max_y = 128
	#Average ores per Chunk [Range: 0-64, Default: 1]
	#Range: 0 ~ 64
	count = 1
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Minimum Y-Level [Range: 0-256, Default: 64]
	#Range: 0 ~ 256
	min_y = 64

["Ore Config: lapis"]
	#Maximum Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	max_y = 16
	#Average ores per Chunk [Range: 0-64, Default: 2]
	#Range: 0 ~ 64
	count = 2
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: redstone"]
	#Maximum Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	max_y = 16
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: copper"]
	#Maximum Y-Level [Range: 0-256, Default: 60]
	#Range: 0 ~ 256
	max_y = 60
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Minimum Y-Level [Range: 0-256, Default: 45]
	#Range: 0 ~ 256
	min_y = 45

["Ore Config: aluminum"]
	#Maximum Y-Level [Range: 0-256, Default: 70]
	#Range: 0 ~ 256
	max_y = 70
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 3]
	#Range: 0 ~ 64
	vein_size = 3
	#Minimum Y-Level [Range: 0-256, Default: 50]
	#Range: 0 ~ 256
	min_y = 50

["Ore Config: silver"]
	#Maximum Y-Level [Range: 0-256, Default: 38]
	#Range: 0 ~ 256
	max_y = 38
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Minimum Y-Level [Range: 0-256, Default: 30]
	#Range: 0 ~ 256
	min_y = 30

["Ore Config: lead"]
	#Maximum Y-Level [Range: 0-256, Default: 40]
	#Range: 0 ~ 256
	max_y = 40
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 3]
	#Range: 0 ~ 64
	vein_size = 3
	#Minimum Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	min_y = 32

["Ore Config: nickel"]
	#Maximum Y-Level [Range: 0-256, Default: 40]
	#Range: 0 ~ 256
	max_y = 40
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 3]
	#Range: 0 ~ 64
	vein_size = 3
	#Minimum Y-Level [Range: 0-256, Default: 25]
	#Range: 0 ~ 256
	min_y = 25

["Ore Config: uranium"]
	#Maximum Y-Level [Range: 0-256, Default: 20]
	#Range: 0 ~ 256
	max_y = 20
	#Average ores per Chunk [Range: 0-64, Default: 4]
	#Range: 0 ~ 64
	count = 4
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 3]
	#Range: 0 ~ 64
	vein_size = 3
	#Minimum Y-Level [Range: 0-256, Default: 5]
	#Range: 0 ~ 256
	min_y = 5

["Ore Config: osmium"]
	#Maximum Y-Level [Range: 0-256, Default: 45]
	#Range: 0 ~ 256
	max_y = 45
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Minimum Y-Level [Range: 0-256, Default: 20]
	#Range: 0 ~ 256
	min_y = 20

["Ore Config: tin"]
	#Maximum Y-Level [Range: 0-256, Default: 55]
	#Range: 0 ~ 256
	max_y = 55
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Minimum Y-Level [Range: 0-256, Default: 40]
	#Range: 0 ~ 256
	min_y = 40

["Ore Config: zinc"]
	#Maximum Y-Level [Range: 0-256, Default: 50]
	#Range: 0 ~ 256
	max_y = 50
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Minimum Y-Level [Range: 0-256, Default: 35]
	#Range: 0 ~ 256
	min_y = 35

["Ore Config: certus_quartz"]
	#Maximum Y-Level [Range: 0-256, Default: 64]
	#Range: 0 ~ 256
	max_y = 64
	#Average ores per Chunk [Range: 0-64, Default: 16]
	#Range: 0 ~ 64
	count = 16
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: charged_certus_quartz"]
	#Maximum Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	max_y = 32
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: fluorite"]
	#Maximum Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	max_y = 32
	#Average ores per Chunk [Range: 0-64, Default: 6]
	#Range: 0 ~ 64
	count = 6
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 12]
	#Range: 0 ~ 64
	vein_size = 12
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: bitumen"]
	#Maximum Y-Level [Range: 0-256, Default: 160]
	#Range: 0 ~ 256
	max_y = 160
	#Average ores per Chunk [Range: 0-64, Default: 25]
	#Range: 0 ~ 64
	count = 25
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 18]
	#Range: 0 ~ 64
	vein_size = 18
	#Minimum Y-Level [Range: 0-256, Default: 40]
	#Range: 0 ~ 256
	min_y = 40

#World Gen - Ore Generation on Strata Stone Type
["Stratum Config: minecraft_stone"]
	active = true

["Stratum Config: minecraft_andesite"]
	active = true

["Stratum Config: create_gabbro"]
	active = true

["Stratum Config: create_limestone"]
	active = true

["Stratum Config: create_scoria"]
	active = true

["Stratum Config: create_weathered_limestone"]
	active = true

["Stratum Config: quark_jasper"]
	active = true

["Stratum Config: quark_marble"]
	active = true

["Stratum Config: quark_slate"]
	active = true

["Ore Config: cinnabar"]
	#Maximum Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	max_y = 15
	#Average ores per Chunk [Range: 0-64, Default: 4]
	#Range: 0 ~ 64
	count = 4
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 5

["Ore Config: apatite"]
	#Maximum Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	max_y = 128
	#Average ores per Chunk [Range: 0-64, Default: 2]
	#Range: 0 ~ 64
	count = 2
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 13]
	#Range: 0 ~ 64
	vein_size = 22
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 64

["Ore Config: sulfur"]
	#Maximum Y-Level [Range: 0-256, Default: 40]
	#Range: 0 ~ 256
	max_y = 15
	#Average ores per Chunk [Range: 0-64, Default: 3]
	#Range: 0 ~ 64
	count = 3
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 0

["Ore Config: potassium_nitrate"]
	#Maximum Y-Level [Range: 0-256, Default: 24]
	#Range: 0 ~ 256
	max_y = 32
	#Average ores per Chunk [Range: 0-64, Default: 3]
	#Range: 0 ~ 64
	count = 3
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 6
	#Minimum Y-Level [Range: 0-256, Default: 0]
	#Range: 0 ~ 256
	min_y = 18

