
[Emojiful]
	#Enable Emoji Selection GUI in the chat text line
	emoji_selector = true
	#Enable Emoji Rendering
	enabled = true
	#Enable Emoji autocomplete in the chat text line
	emoji_autocomplete = true
	#Replace short versions of emoji like :) into :smile: so they can be rendered as emoji
	short_emoji_replacement = true
	#Load animated emojis, if disabled they will be a still image
	gifs = true

	[Emojiful.EmojiTypes]
		#Loads Twemojis used in sites like Twitter and Discord
		twemoji = true
		#Loads custom emojis provided by Emojiful
		custom = true
		#Loads datapack emojis provided by the server you join
		datapack = true

[ProfanityFilter]
	#Replacement word for the profanity filter
	replacement = ":swear:"
	#Enable Profanity Filter, this will replace bad words with emoji
	enabled = false

