
[Client]
	#The line offset for information rendered on the HUD.
	#Range: 0 ~ 50
	lineOffset = 1
	#The side for information rendered on the HUD. Ex: LEFT, RIGHT
	#Allowed Values: LEFT, RIGHT
	overlaySide = "LEFT"
	#Displays Package Controller information even while chat is open.
	displayWithChatOpen = true

