
#Settings not loaded on servers.
[client]

	#Opt-out settings
	[client.optout]
		#Disable CTRL-SHIFT item tooltip display.
		without_tooltips = false
		#Disable all TERs (tile entity renderers).
		without_ters = false

