
#Settings affecting the logical server side.
[server]

	#Opt-out settings
	[server.optout]
		#Prevent blocks from being opt'ed by registry name ('*' wildcard matching, comma separated list, whitespaces ignored. Evaluated before all other opt-out checks. You must match the whole name, means maybe add '*' also at the begin and end. Example: '*wood*,*steel*' includes everything that has 'wood' or 'steel' in the registry name.The matching result is also traced in the log file.
		pattern_includes = ""
		#Opt-out any block by its registry name ('*' wildcard matching, comma separated list, whitespaces ignored. You must match the whole name, means maybe add '*' also at the begin and end. Example: '*wood*,*steel*' excludes everything that has 'wood' or 'steel' in the registry name. The matching result is also traced in the log file. 
		pattern_excludes = ""

	#Miscellaneous settings
	[server.miscellaneous]
		#Enables experimental features. Use at own risk.
		with_experimental = false
		#Enable that devices are dropped as item also in creative mode, allowing  to relocate them with contents and settings.
		with_creative_mode_device_drops = false
		#Enable debug log messages for trouble shooting. Don't activate if not really needed, this can spam the log file.
		with_debug_logging = false

