
[Client]
	#When looking at an Entangled Block, should its bound block be highlighted?
	#Requires a world reload
	#Allowed Values: true, false  Default: true
	renderBlockHighlight = true

[General]
	#Can entangled blocks be bound between different dimensions? Previously bound entangled blocks won't be affected.
	#Requires a world reload
	#Allowed Values: true, false  Default: true
	allowDimensional = false
	#What is the max range in which entangled blocks can be bound? Only affects blocks in the same dimension. -1 for infinite range. Previously bound entangled blocks won't be affected.
	#Requires a world reload
	#Allowed Range: -1 ~ 2147483647  Default: -1
	maxDistance = 1000

