
#general settings
[general]
	#Disable the anchors?
	disableAnchors = false
	#Disable the Muffle button in the player inventory?
	disableInventoryButton = false
	#Blacklisted Sounds - add the name of the sounds to blacklist, separated with comma
	forbiddenSounds = ["ui.", "music.", "ambient."]

