#Enable/Disable debug mode
debug = false

[SmokeContainers]
	#Maximum length of the vent pipe for smoke or gas transmition
	#Range: 1 ~ 64
	maxVentPipeLength = 32
	#Maximum distance from vent to the gas block to inhale
	#Range: 1 ~ 16
	ventInhaleDistance = 4
	#Maximum amount of blocks that will be checked when searching for multiblock boundaries.
	#Range: 1 ~ 512
	maxBlocksInMultiblock = 81

