
#General settings for the mod.
[general]
	#Should pets be protected from damage dealt by their owners?
	protectPetsFromOwner = true
	#Should pets be protected from damage dealt by other pets with the same owner?
	protectPetsFromOtherPets = true
	#Should children mobs be protected from damage?
	protectChildren = false
	#Should damage against friendly mobs be reflected back on the damage dealer?
	reflectDamage = false

