#Noise added to map to make it look less plastic
#Range: 0.0 ~ 0.5
noise = 0.05
#Enables minimap to show up in corner
#Allowed Values: DISABLED, BOTTOM_LEFT, LEFT, TOP_LEFT, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
minimap = "DISABLED"
#Scale of minimap
#Range: 0.25 ~ 4.0
minimap_scale = 1.0
#Minimap will not rotate
minimap_locked_north = true
#Show waypoints on minimap
minimap_waypoints = true
#Show entities on minimap
minimap_entities = true
#Show entity heads on minimap
minimap_entity_heads = true
#Show player heads on minimap
minimap_player_heads = true
#Entities in minimap will be larger
minimap_large_entities = false
#Show XYZ under minimap
minimap_xyz = true
#Show biome under minimap
minimap_biome = true
#Blurs minimap
minimap_blur = true
#Adds NWSE compass inside minimap
minimap_compass = true
#Shadow intensity
#Range: 0.0 ~ 0.3
shadows = 0.1
#Chunk grid overlay in large map
chunk_grid = false
#Reduces color palette to 256 colors
reduced_color_palette = false
#Color intensity
#Range: 0.0 ~ 1.0
saturation = 1.0
#Minimap visibility
#Range: 0 ~ 255
minimap_visibility = 255
#Enables debug info
debug_info = false

