#The names of the Dimensions for the Death Note
dimension_names = ["minecraft:overworld=Overworld", "minecraft:nether=Nether", "minecraft:the_end=The End"]
#The date format outputted by clicking the gravestone or displayed in the death note
grave_date_format = "yyyy/MM/dd HH:mm:ss"
#If this is set to true the players head will be rendered on the gravestone when there is a full block under it
render_skull = true
#The color of the text at the gravestone (Hex RGB)
grave_text_color = "FFFFFF"

