
#Configuration for Inventory Essentials
[client]
	#Should holding shift and moving your mouse over items quick-transfer them without requiring each to be clicked?
	enableShiftDrag = true
	#Should ctrl-clicking only move one item at a time instead of the full stack?
	enableSingleTransfer = true
	#Use the client implementation even on servers that have the mod installed - only useful for development purposes.
	forceClientImplementation = false
	#Should shift-ctrl-clicking move all items of the same type at once?
	enableBulkTransfer = true

