
[general]
	#Modify the rate of smoke produced by a tug. Min 0, Max 1, Default 0.4
	#Range: 0.0 ~ 1.0
	tugSmoke = 0.4
	#Disable indicator beacons for tug route item. Default false.
	disableTugRouteBeacons = false

