
[Login-settings]
	#Time in ticks the logging player is invulnerable, 20 ticks = 1sec. Default is 5secs = 100 ticks
	#Range: 0 ~ 50000
	invulnerabilityTime = 100
	#Max distance in blocks(2d) the invulnerability lasts, default: 4
	#Range: 1 ~ 200
	maxDistance = 4

[debug]
	#Wether to enable debug log outputs, default: false
	debugLog = false

