
#Mapper Base General Config
[general_config]
	#Enable the Tag Viewer (press CTRL while cursor being on item). This is client-side only. [default: false]
	EnableTagViewer = false
	#Enable the logs for ore genration, useful to check if your config file is correct. This is client-side only. [default: false]
	EnableGenLogs = false

