
[formatting]
	#How the mod name should be formatted in the tooltip. Leave blank to disable. Valid values:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white, obfuscated, bold, strikethrough, underline, italic
	modNameFormat = "blue italic"

