
#MobGriefing settings
[mobGriefing]
	#blaze mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	blaze = "DEFAULT"
	#cow mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	cow = "DEFAULT"
	#creeper mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	creeper = "DEFAULT"
	#ender_dragon mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	ender_dragon = "DEFAULT"
	#enderman mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	enderman = "FALSE"
	#evoker mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	evoker = "DEFAULT"
	#fox mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	fox = "DEFAULT"
	#ghast mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	ghast = "DEFAULT"
	#horse mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	horse = "DEFAULT"
	#husk mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	husk = "DEFAULT"
	#pig mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	pig = "DEFAULT"
	#piglin mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	piglin = "DEFAULT"
	#piglin_brute mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	piglin_brute = "DEFAULT"
	#ravager mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	ravager = "DEFAULT"
	#rabbit mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	rabbit = "DEFAULT"
	#sheep mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	sheep = "DEFAULT"
	#silverfish mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	silverfish = "DEFAULT"
	#snow_golem mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	snow_golem = "DEFAULT"
	#strider mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	strider = "DEFAULT"
	#villager mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	villager = "DEFAULT"
	#wither mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	wither = "DEFAULT"
	#zombie mobGriefing
	#Allowed Values: DEFAULT, TRUE, FALSE
	zombie = "DEFAULT"

