"Allow all items to be added" = false
"Morph in the offhand instead of mainhand" = false
"Whitelisted Items" = ["botania:twig_wand", "immersiveengineering:tool", "bloodmagic:ritual_reader", "bloodmagic:ritualtinkerer", "astralsorcery:wand", "transport:rail_breaker", "storagedrawers:drawer_key", "resourcefulbees_scraper", "ars_nouveau:dominion_wand"]
"Whitelisted Names" = ["wrench", "screwdriver", "hammer", "rotator", "configurator", "crowbar"]
"Blacklisted Mods" = []
"Mod Aliases" = ["nautralpledge=botania", "mythicbotany=botania", "rsrequestify=refinedstorage", "framedcompactdrawers=storagedrawers", "extrastorage=refinedstorage", "thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "animus=bloodmagic", "integrateddynamics=integratedtunnels", "mekanismgenerators=mekanism", "mekanismtools=mekanism", "deepresonance=rftools", "xnet=rftools"]

