
[general]
	#Whether to ignore banners when attached to an interactable block or not.
	"Ignore banners" = true
	#Whether to ignore wall signs when attached to an interactable block or not.
	"Ignore wall signs" = true
	#Whether shift-click is required to ignore signs, when Quark is installed.
	"Shift-click to ignore signs (Quark)" = false
	#Whether to ignore paintings when attached to an interactable block or not.
	"Ignore paintings" = true
	#Disable default behaviour of item frames rotation display, when not sneaking (Recommended when ignoring item frames is enabled)
	"Turn off item rotation" = true
	#Whether to ignore item frames when attached to an interactable block or not.
	"Ignore item frames" = true

