storagenetwork = false
tconstruct = true
fastfurnaceminusreplacement = false
sophisticatedbackpacks = true
fastfurnace = true
craftingstation = true
ironfurnaces = false
occultism = true
jei = true
extendedcrafting = true
fastbenchminusreplacement = false
refinedstorageaddons = true
craftingcraft = false
toms_storage = false
refinedstorage = true
prettypipes = true
fastsuite = true
fastbench = true
cyclic = false
appliedenergistics2 = false

