
[General]
	#How many ticks it takes for process a recipe in the centrifuge. Default 300.
	#Range: > 20
	centrifugeProcessingTime = 300
	#[UNUSED] Use items to change the type of a bee.
	#If false, productive bees can only be obtained through breeding. Default false.
	enableItemConverting = false
	#Deprecated: Moved to spawning recipe.
	#Range: > 20
	nestRepopulationCooldown = 36000
	#How much FE to use per tick for a powered centrifuge when processing an item. Default 10.
	#Range: > 1
	centrifugePowerUse = 10
	#Bees will create combs instead of raw resource. Combs will need to be processed in a centrifuge. Default true.
	enableCombProduce = true
	#How often should a bee attempt to generate items while in the hive. Default 500.
	#Range: > 20
	itemTickRate = 500
	#How many ticks it takes for process a recipe in the powerd centrifuge. Default 100.
	#Range: > 20
	centrifugePoweredProcessingTime = 100
	#A priority list of Mod IDs that results of comb output should stem from, aka which mod you want the copper to come from. Eg: mekanism,silents_mekanism,immersiveengineering
	preferredOres = ["emendatusenigmatica", "minecraft", "immersiveengineering", "create", "mekanism", "jaopca", "kubejs", "appliedenergistics2", "pneumaticcraft", "occultism", "tmechworks", "industrialforegoing", "botania", "quark", "pedestals"]
	#How many bees can fit in a bee bom. Default is 10
	#Range: 1 ~ 50
	numberOfBeesPerBomb = 10

["Hive Upgrades"]
	#Chance for a bee to produce an offspring after a hive visit.
	#Range: 0.0 ~ 1.0
	breedingChance = 0.05
	#Multiplier per productivity upgrade installed in the hive.
	#Range: 1.0 ~ 2.147483647E9
	productivityMultiplier = 1.8
	#Time bonus gained from time upgrade. 0.2 means 20% reduction of a bee's time inside the hive.
	#Range: 0.0 ~ 1.0
	timeBonus = 0.2
	#Time penalty from installing the comb block upgrade. 1.4 means 140% increase of a bee's time inside the hive.
	#Range: 1.0 ~ 2.147483647E9
	combBlockTimeodifier = 1.4

["Bee attributes"]
	#Number of ticks between effects on nearby entities
	#Range: > 20
	ticks = 2337
	#Chance that a bee will take damage while leashed in a hostile environment
	#Range: 0.0 ~ 1.0
	damageChance = 0.1
	#Chance to increase behavior (nocturnal trait) while leashed in a hostile environment.
	#Range: 0.0 ~ 1.0
	behaviorChance = 0.1
	#Chance to increase tolerance (rain or thunder tolerance trait) while leashed in a hostile environment.
	#Range: 0.0 ~ 1.0
	toleranceChance = 0.1
	#Chance to extract genes from a bottle of bee material.
	#Range: 0.0 ~ 1.0
	genExtractChance = 0.85

[Worldgen]
	"enable_productivebees:acacia_wood_nest" = true
	"enable_productivebees:gravel_nest" = true
	"enable_productivebees:glowstone_nest" = true
	"enable_productivebees:end_stone_nest" = true
	"enable_productivebees:jungle_wood_nest" = true
	"enable_productivebees:sugar_cane_nest" = true
	"enable_productivebees:nether_quartz_nest" = true
	"enable_productivebees:coarse_dirt_nest" = true
	"enable_productivebees:nether_gold_nest" = true
	"enable_productivebees:stone_nest" = true
	"enable_productivebees:nether_brick_nest" = true
	"enable_productivebees:snow_nest" = true
	"enable_productivebees:sand_nest" = true
	"enable_productivebees:obsidian_nest" = true
	"enable_productivebees:slimy_nest" = true
	"enable_productivebees:soul_sand_nest" = true
	#Which nests should generate in the world. Nest will still be craftable and attract bees when placed in the world.
	"enable_productivebees:oak_wood_nest" = true
	"enable_productivebees:spruce_wood_nest" = true
	"enable_productivebees:birch_wood_nest" = true
	"enable_productivebees:dark_oak_wood_nest" = true

[Bees]
	#Range: 0.0 ~ 1.0
	spawnUndeadBeesChance = 0.01
	#Spawn skeletal and zombie bees as night?
	spawnUndeadBees = true

