
[general]
	#True if player UI has plague hearts render when the effect is active.
	"Plague Heart Overlay" = true
	#Skip experimental GUI settings from vanilla when loading a world.
	"Skip Experimental Settings GUI" = true
	#True if rats flutes can occasionally make a funny sound.
	"Funny Rat Flute Sound" = true

