
[grid]
	#Whether the Grid should use a large font for stack quantity display
	largeFont = false
	#Whether the Grid should display a detailed tooltip when hovering over an item or fluid
	detailedTooltip = true
	#Whether the Grid should prevent sorting while the shift key is held down
	preventSortingWhileShiftIsDown = true
	#The maximum amount of rows that the Grid can show when stretched
	#Range: > 3
	maxRowsStretch = 2147483647

[crafterManager]
	#The maximum amount of rows that the Crafter Manager can show when stretched
	#Range: > 3
	maxRowsStretch = 2147483647

