
["Witch Huts"]
	#
	# Add the ID/resource location of the biome you don't want
	# RS's witch huts to spawn in. Separate each ID with a comma ,
	#   Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedWitchHutBiomes = " "
	#
	# Add Oak Witch Huts to modded Forest biomes that are not birch or dark oak.
	#Range: 1 ~ 1001
	witchHutsOakMaxChunkDistance = 48
	#
	# Add Oak Witch Huts to modded Forest biomes that are not birch or dark oak.
	addWitchHutsOakToModdedBiomes = true
	#
	# Add Taiga Witch Huts to modded Taiga biomes.
	#Range: 1 ~ 1001
	witchHutsTaigaMaxChunkDistance = 48
	#
	# Add Taiga Witch Huts to modded Taiga biomes.
	addWitchHutsTaigaToModdedBiomes = true
	#
	# Add Giant Tree Taiga Witch Huts to modded Giant Tree Taiga biomes.
	#Range: 1 ~ 1001
	witchHutsGiantTreeTaigaMaxChunkDistance = 48
	#
	# Add Giant Tree Taiga Witch Huts to modded Giant Tree Taiga biomes.
	addWitchHutsGiantTreeTaigaToModdedBiomes = true
	#
	# Add Birch Witch Huts to modded Birch biomes.
	#Range: 1 ~ 1001
	witchHutsBirchMaxChunkDistance = 48
	#
	# Add Birch Witch Huts to modded Birch biomes.
	addWitchHutsBirchToModdedBiomes = true
	#
	# Add Dark Forest Witch Huts to modded Dark Forest biomes.
	#Range: 1 ~ 1001
	witchHutsDarkForestMaxChunkDistance = 48
	#
	# Add Dark Forest Witch Huts to modded Dark Forest biomes.
	addWitchHutsDarkForestToModdedBiomes = true

