
[Shipwrecks]
	#
	# Add the ID/resource location of the biome you don't want
	# RS's shipwrecks to spawn in. Separate each ID with a comma ,
	#   Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedShipwreckBiomes = " "
	#
	# Add End Shipwreck to modded End biomes.
	addEndShipwreckToModdedBiomes = true
	#
	# How rare are End Shipwreck in End Highlands biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	endShipwreckMaxChunkDistance = 15
	#
	# Add Nether Bricks Shipwreck to modded non-warped or non-crimson Nether biomes.
	addNetherBricksShipwreckToModdedBiomes = true
	#
	# How rare are Nether Bricks Shipwreck in any non-warped or non-crimson Nether biome.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherBricksShipwreckMaxChunkDistance = 51
	#
	# Add Crimson Shipwreck to modded Crimson-named Nether biome.
	addCrimsonShipwreckToModdedBiomes = true
	#
	# How rare are Crimson Shipwreck in Crimson Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	crimsonShipwreckMaxChunkDistance = 41
	#
	# Add Warped Shipwreck to modded Warped Nether biomes.
	addWarpedShipwreckToModdedBiomes = true
	#
	# How rare are Warped Shipwreck in Warped Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	warpedShipwreckMaxChunkDistance = 41

