#Maximum health of the common blob
#Range: > 0
commonBlobMaxHealth = 30
#Maximum health of the rare blob
#Range: > 0
rareBlobMaxHealth = 250
#Maximum health of the legendary blob
#Range: > 0
legendaryBlobMaxHealth = 5000

