
#Simple Discord Rich Presence config
[common]
	#Client ID
	#Range: -9223372036854775808 ~ 9223372036854775807
	clientID = 737737067055808513
	#Enable Discord Rich Presence
	discordRP = true

