
["Add New Version"]
	#ModID's of the ServerConfigs that will be deleted when a world with a version lower than this version is loaded the first time. Comma Separated list. (ServerConfig without -server.toml)
	toDelete = ""
	#Version Number. VersionNumbers are simple Integers. Use a number larger than the last version.
	#Range: > 0
	newVersion = 0

["File Deleter"]
	#By default Folders are only deleted if they are empty. Set to true to change that.
	deleteFoldersWithContent = false
	#This is intended for deleting datapacks and/or craft tweaker scripts. The file will be deleted every launch if it exists! No access to saves or world folder. Specify the path to the file. Comma Separated List. Example: scripts/badscript.zs
	filesToDelete = "kubejs/assets/mythicbotany/lang/en_us.json,kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/spirit_fire.js,kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools.js,kubejs/data/tetra/loot_tables/actions/geode.json,kubejs/assets/enigmatica/tips/paraglider.json,kubejs/data/minecraft/loot_tables/chests/end_city_treasure.json,config/configswapper/expert/randompatches.txt,config/configswapper/normal/randompatches.txt,config/configswapper/normal/occultism.txt,config/configswapper/normal/immersiveengineering.txt,config/configswapper/normal/astralsorcery.txt,config/configswapper/expert/occultism.txt,config/configswapper/expert/immersiveengineering.txt,config/configswapper/expert/astralsorcery.txt,config/configswapper/normal/patchouli-client.toml,config/configswapper/expert/patchouli-client.toml"

["Version History"]
	#Editing these values will not affect any worlds that are already on that version.
	history = "1=travel_anchors;2=astralsorcery;3=valhelsia_structures,immersiveengineering,curios;4=valhelsia_structures,immersiveengineering,curios;5=ensorcellation,curios;6=create;7=rftoolsbuilder;8=computercraft;9=refinedstorage;10=rftoolsdim;11=astralsorcery;12=solcarrot;13=moredragoneggs;"

