
#General settings
[general]
	#How often should the server send tps updates to clients
	#Range: 100 ~ 600
	refreshTicks = 200
	#Only ops can see tps information, this is to stop tps hunters
	opOnlyMode = false

