placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = false
snowAccumulationOnSpecialBlocks = true
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = false
snowNeverMelt = false
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
#If you want to uninstall this mod, you probably want to make snow-covered blocks back to normal.
retainOriginalBlocks = false

