#Set this to false to disable snow under trees when first generating chunks.
enable_biome_feature = true
#Set this to false to disable snow under trees when it's snowing.
enable_when_snowing = true
#Add biome IDs here to exempt biomes from being affected by the mod (surrounded by ""). You can find the biome ID of the biome you're currently in on the F3 screen.
#For example, the biome ID of the plains biome looks like this: minecraft:plains
filtered_biomes = []

