
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["void_upgrade:true", "compacting_upgrade:true", "advanced_restock_upgrade:true", "diamond_backpack:true", "smelting_upgrade:true", "filter_upgrade:true", "magnet_upgrade:true", "advanced_magnet_upgrade:true", "deposit_upgrade:true", "iron_backpack:true", "stonecutter_upgrade:true", "backpack:true", "feeding_upgrade:true", "advanced_pickup_upgrade:true", "jukebox_upgrade:true", "everlasting_upgrade:true", "advanced_filter_upgrade:true", "inception_upgrade:true", "crafting_upgrade:true", "auto_smelting_upgrade:true", "pickup_upgrade:true", "stack_upgrade_tier_4:true", "stack_upgrade_tier_2:true", "stack_upgrade_tier_3:true", "stack_upgrade_tier_1:true", "upgrade_base:true", "refill_upgrade:true", "advanced_compacting_upgrade:true", "gold_backpack:true", "advanced_deposit_upgrade:true", "advanced_void_upgrade:true", "restock_upgrade:true", "advanced_tool_swapper_upgrade:true", "tool_swapper_upgrade:true", "netherite_backpack:true", "tank_upgrade:true", "advanced_feeding_upgrade:true", "battery_upgrade:true", "advanced_pump_upgrade:true", "pump_upgrade:true", "xp_pump_upgrade:true", "auto_smoking_upgrade:true", "smoking_upgrade:true", "auto_blasting_upgrade:true", "blasting_upgrade:true"]
	#List of items that are not allowed to be put in backpacks - e.g. "minecraft:shulker_box"
	disallowedItems = []
	#Turns on/off loot added to various vanilla chest loot tables
	chestLootEnabled = true
	#Turns on/off item fluid handler of backpack in its item form. There are some dupe bugs caused by default fluid handling implementation that manifest when backpack is drained / filled in its item form in another mod's tank and the only way to prevent them is disallowing drain/fill in item form altogether
	itemFluidHandlerEnabled = true

	#Leather Backpack Settings
	[common.leatherBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 27
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 1

	#Iron Backpack Settings
	[common.ironBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 54
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 2

	#Gold Backpack Settings
	[common.goldBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 81
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 3

	#Diamond Backpack Settings
	[common.diamondBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 108
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 5

	#Netherite Backpack Settings
	[common.netheriteBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 120
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 7

	#Compacting Upgrade Settings
	[common.compactingUpgrade]
		#Number of Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Compacting Upgrade Settings
	[common.advancedCompactingUpgrade]
		#Number of Advanced Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Deposit Upgrade Settings
	[common.depositUpgrade]
		#Number of Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Deposit Upgrade Settings
	[common.advancedDepositUpgrade]
		#Number of Advanced Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Feeding Upgrade Settings
	[common.feedingUpgrade]
		#Number of Feeding Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Filter Upgrade Settings
	[common.filterUpgrade]
		#Number of Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Filter Upgrade Settings
	[common.advancedFilterUpgrade]
		#Number of Advanced Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Magnet Upgrade Settings
	[common.magnetUpgrade]
		#Number of Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 3

	#Advanced Magnet Upgrade Settings
	[common.advancedMagnetUpgrade]
		#Number of Advanced Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 5

	#Pickup Upgrade Settings
	[common.pickupUpgrade]
		#Number of Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Pickup Upgrade Settings
	[common.advancedPickupUpgrade]
		#Number of Advanced Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Refill Upgrade Settings
	[common.refillUpgrade]
		#Number of Refill Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 6
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Restock Upgrade Settings
	[common.restockUpgrade]
		#Number of Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Restock Upgrade Settings
	[common.advancedRestockUpgrade]
		#Number of Advanced Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Void Upgrade Settings
	[common.voidUpgrade]
		#Number of Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Void Upgrade Settings
	[common.advancedVoidUpgrade]
		#Number of Advanced Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Smelting Upgrade Settings
	[common.smeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Advanced Feeding Upgrade Settings
	[common.advancedFeedingUpgrade]
		#Number of Advanced Feeding Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Stack Upgrade Settings
	[common.stackUpgrade]
		#List of items that are not supposed to stack in backpack even when stack upgrade is inserted. Item registry names are expected here.
		nonStackableItems = []

	#Smoking Upgrade Settings
	[common.smokingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Blasting Upgrade Settings
	[common.blastingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Auto-Smelting Upgrade Settings
	[common.autoSmeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4

	#Auto-Smoking Upgrade Settings
	[common.autoSmokingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4

	#Auto-Blasting Upgrade Settings
	[common.autoBlastingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4

	#Inception Upgrade Settings
	[common.inceptionUpgrade]
		#Allows / Disallows backpack upgrades to work with inventories of Backpacks in the Backpack with Inception Upgrade
		upgradesUseInventoriesOfBackpacksInBackpack = true
		#Allows / Disallows upgrades to be functional even when they are in Backpacks in the inventory of Backpack with Inception Upgrade
		upgradesInContainedBackpacksAreFunctional = true

	#Tool Swapper Upgrade Settings
	[common.toolSwapperUpgrade]
		#Number of tool filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Tank Upgrade Settings
	[common.tankUpgrade]
		#Capacity in mB the tank upgrade will have per row of backpack slots
		#Range: 500 ~ 20000
		capacityPerSlotRow = 4000
		#Ratio that gets applied (multiplies) to inventory stack multiplier before this is applied to max energy of the battery and max in/out. Value lower than 1 makes stack multiplier affect the max energy less, higher makes it affect the max energy more. 0 turns off stack multiplier affecting battery upgrade
		#Range: 0.0 ~ 5.0
		stackMultiplierRatio = 1.0
		#Cooldown between fill/drain actions done on fluid containers in tank slots. Only fills/drains one bucket worth to/from container after this cooldown and then waits again.
		#Range: 1 ~ 100
		autoFillDrainContainerCooldown = 20
		#How much FE can be transfered in / out per operation. This is a base transfer rate and same as max storage gets multiplied by number of rows in backpack and stack multiplier.
		#Range: 1 ~ 1000
		maxInputOutput = 20
		#Energy in FE the battery upgrade will have per row of backpack slots
		#Range: 500 ~ 50000
		energyPerSlotRow = 10000

	#Pump Upgrade Settings
	[common.pumpUpgrade]
		#Number of fluid filter slots
		#Range: 1 ~ 20
		filterSlots = 4
		#How much mB can be transfered in / out per operation. This is a base transfer rate that gets multiplied by number of rows in backpack and stack multiplier.
		#Range: 1 ~ 1000
		maxInputOutput = 20
		#Ratio that gets applied (multiplies) to inventory stack multiplier before this is applied to max input/output value. Value lower than 1 makes stack multiplier affect the capacity less, higher makes it affect the capacity more. 0 turns off stack multiplier affecting input/output
		#Range: 0.0 ~ 5.0
		stackMultiplierRatio = 1.0

	#Xp Pump Upgrade Settings
	[common.xpPumpUpgrade]
		#Whether xp pump can mend items with mending. Set false here to turn off the feature altogether.
		mendingOn = true
		#How many experience points at a maximum would be used to mend an item per operation (every 5 ticks and 1 xp point usually translates to 2 damage repaired).
		#Range: 1 ~ 20
		maxXpPointsPerMending = 5

	#Settings for Spawning Entities with Backpack
	[common.entityBackpackAdditions]
		#Chance of an entity spawning with Backpack
		#Range: 0.0 ~ 1.0
		chance = 0.01
		#Turns on/off addition of loot into backpacks
		addLoot = true
		#Turns on/off buffing the entity that wears backpack with potion effects. These are scaled based on how much loot is added.
		buffWithPotionEffects = true
		#Turns on/off buffing the entity that wears backpack with additional health. Health is scaled based on backpack tier the mob wears.
		buffHealth = true
		#Turns on/off equiping the entity that wears backpack with armor. What armor material and how enchanted is scaled based on backpack tier the mob wears.
		equipWithArmor = true
		#Map of entities that can spawn with backpack and related loot tables (if adding a loot is enabled) in format of "EntityRegistryName|LootTableName"
		entityLootTableList = ["minecraft:creeper|minecraft:chests/desert_pyramid", "minecraft:drowned|minecraft:chests/shipwreck_treasure", "minecraft:enderman|minecraft:chests/end_city_treasure", "minecraft:evoker|minecraft:chests/woodland_mansion", "minecraft:husk|minecraft:chests/desert_pyramid", "minecraft:piglin|minecraft:chests/bastion_bridge", "minecraft:piglin_brute|minecraft:chests/bastion_treasure", "minecraft:pillager|minecraft:chests/pillager_outpost", "minecraft:skeleton|minecraft:chests/simple_dungeon", "minecraft:stray|minecraft:chests/igloo_chest", "minecraft:vex|minecraft:chests/woodland_mansion", "minecraft:vindicator|minecraft:chests/woodland_mansion", "minecraft:witch|minecraft:chests/buried_treasure", "minecraft:wither_skeleton|minecraft:chests/nether_bridge", "minecraft:zombie|minecraft:chests/simple_dungeon", "minecraft:zombie_villager|minecraft:chests/village/village_armorer", "minecraft:zombified_piglin|minecraft:chests/bastion_other"]
		#List of music discs that are not supposed to be played by entities
		discBlockList = ["botania:record_gaia_1", "botania:record_gaia_2"]
		#Turns on/off a chance that the entity that wears backpack gets jukebox upgrade and plays a music disc.
		playJukebox = true
		#Chance of mob dropping backpack when killed by player
		#Range: 0.0 ~ 1.0
		backpackDropChance = 0.085
		#Chance increase per looting level of mob dropping backpack
		#Range: 0.0 ~ 0.2
		lootingChanceIncreasePerLevel = 0.01

	[common.nerfs]
		#Determines if too many backpacks in player's inventory cause slowness to the player
		tooManyBackpacksSlowness = false
		#Maximum number of backpacks in player's inventory that will not cause slowness
		#Range: 1 ~ 27
		maxNumberOfBackpacks = 3
		#Ratio of slowness levels per every backpack above the maximum number allowed. (number of backpacks above the max gets multiplied by this number and ceiled)
		#Range: 0.1 ~ 5.0
		slownessLevelsPerAdditionalBackpack = 1.0

