
#all these don't actually disable blocks anymore, they just remove their recipe and remove them from the creative tabs(like all other mods do)
#to access server configuration go into /saves/serverconfigs
[general]
	#enable creative tab
	creative_tab = false
	#set to false to disable custom dispenser behaviors (filling jars) if for some reason they are causing trouble
	dispensers = true
	#creates a creative tab full of filled jars
	jar_tab = false

#Enable and disable blocks / entities
[registration]

	[registration.blocks]
		planter = true
		clock_block = true
		pedestal = false
		wind_vane = true
		redstone_illuminator = false
		notice_board = true
		crank = false
		jar = false
		faucet = true
		turn_table = false
		piston_launcher = true
		speaker_block = true
		sign_post = true
		hanging_sign = true
		bellows = true
		sconce = true
		sconce_green = true
		sconce_ender = true
		sconce_soul = true
		candelabra = true
		cage = false
		item_shelf = true
		sconce_lever = true
		cog_block = false
		candle_holder = true
		globe = true
		hourglass = true
		sack = false
		blackboard = false
		safe = true
		copper_lantern = true
		flute = true
		gold_trapdoor = true
		gold_door = true
		bamboo_spikes = true
		stone_lamp = false
		checker_block = true
		netherite_door = true
		netherite_trapdoor = true
		pancake = true
		lock_block = true
		flax = true
		rope = true
		rope_arrow = true
		pulley_block = true
		fodder = true
		bomb = true
		#WIP
		laser_block = false
		#WIP
		flag = true
		magma_cream_block = false

	[registration.entities]
		firefly = true

