
#Here are configs that need reloading to take effect
[initialization]

	[initialization.general]
		#Enable Creative Tab
		creative_tab = false
		#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
		dispensers = true
		#Creates a creative tab full of filled jars
		jar_tab = false
		#Enables custom Configured config screen
		custom_configured_screen = true

	[initialization.blocks]
		planter = true
		clock_block = true
		pedestal = true
		wind_vane = true
		redstone_illuminator = true
		notice_board = true
		crank = true
		jar = true
		faucet = true
		turn_table = true
		piston_launcher = true
		speaker_block = true
		sign_post = true
		hanging_sign = true
		bellows = true
		sconce = true
		sconce_green = false
		candelabra = true
		cage = true
		item_shelf = true
		sconce_lever = true
		cog_block = true
		candle_holder = true
		globe = true
		hourglass = true
		sack = true
		blackboard = true
		safe = true
		copper_lantern = true
		flute = true
		gold_trapdoor = true
		gold_door = true
		bamboo_spikes = true
		stone_lamp = true
		checker_block = true
		netherite_door = true
		netherite_trapdoor = true
		pancake = true
		lock_block = true
		flax = true
		rope = true
		rope_arrow = true
		pulley_block = true
		fodder = true
		bomb = true
		crimson_lantern = true
		magma_cream_block = false
		flag = false
		goblet = true
		raked_gravel = true
		statue = true
		iron_gate = true
		#WIP
		laser_block = false

	[initialization.entities]
		firefly = true

