
#Here are configs that need reloading to take effect
[initialization]

	[initialization.general]
		#Enable Creative Tab
		creative_tab = false
		#Enables custom Configured config screen
		custom_configured_screen = false
		#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
		dispensers = true
		#Creates a creative tab full of filled jars
		jar_tab = false

	[initialization.entities]
		firefly = true

	[initialization.blocks]
		clock_block = true
		speaker_block = true
		sack = false
		#WIP
		laser_block = false
		bellows = true
		hanging_sign = true
		bomb = true
		#WIP
		amethyst_arrow = true
		cage = true
		stone_tile = true
		blaze_rod = true
		bamboo_spikes = true
		hourglass = true
		raked_gravel = true
		jar = true
		stick = true
		rope_arrow = true
		checker_block = true
		slingshot = true
		wattle_and_daub = true
		stone_lamp = false
		cog_block = true
		crank = false
		copper_lantern = true
		pancake = true
		statue = true
		iron_gate = true
		netherite_trapdoor = true
		bamboo_spikes_tipped = true
		fodder = true
		wrench = true
		end_stone_lamp = true
		globe = true
		sconce = true
		candelabra = true
		timber_frame = true
		spring_launcher = true
		safe = true
		sconce_lever = true
		#WIP
		present = true
		sign_post = true
		pedestal = false
		blackboard = false
		netherite_door = true
		candle_holder = true
		flint_block = true
		flag = true
		candy = true
		rope = true
		notice_board = true
		redstone_illuminator = true
		crimson_lantern = true
		lock_block = true
		flax = true
		planter = true
		wind_vane = true
		item_shelf = true
		turn_table = false
		faucet = true
		daub = true
		blackstone_lamp = true
		gold_trapdoor = true
		feather_block = true
		magma_cream_block = false
		deepslate_lamp = true
		goblet = true
		sconce_green = false
		flute = true
		pulley_block = true
		gold_door = true
		shulker_shell = true

