
#Server side blocks configs
[blocks]

	[blocks.speaker_block]
		#maximum range
		#Range: 0 ~ 256
		range = 64

	[blocks.bellows]
		#bellows pushes air following this equation: 
		#air=(sin(2PI*ticks/period)<0), with period = base_period-(redstone_power-1)*power_scaling 
		#represents base period at 1 power
		#Range: 1 ~ 512
		base_period = 78
		#entities with velocity greated than this won't be pushed
		#Range: 0.0 ~ 16.0
		power_scaling = 2.0
		#velocity increase uses this equation: 
		#vel = base_vel*((range-entity_distance)/range) with base_vel = base_velocity_scaling/period 
		#note that the block will push further the faster it's pulsing
		#Range: 0.0 ~ 64.0
		base_velocity_scaling = 5.0
		#sets velocity changed flag when pushing entities +
		#causes pushing animation to be smooth client side but also restricts player movement when being pushed
		velocity_changed_flag = true
		#note that it will still only keep alive the two fire blocks closer to it
		#Range: 0 ~ 16
		range = 5

	[blocks.spring_launcher]
		#spring launcher launch speed
		#Range: 0.0 ~ 16.0
		velocity = 1.5
		#fall distance needed to trigger the automatic spring launch
		#Range: 0 ~ 512
		fall_height_required = 5

	[blocks.turn_table]
		#can rotate entities standing on it?
		rotate_entities = true
		#blocks that can't be rotated. Some special ones like chests, beds and pistons are already hardcoded
		blacklist = ["minecraft:end_portal_frame"]

	[blocks.jar]
		#jar liquid capacity: leave at 12 for pixel accuracy
		#Range: 0 ~ 1024
		capacity = 12
		#allow right click to instantly eat or drink food or potions inside a jar.
		#Disable if you think this ability is op. Cookies are excluded
		drink_from_jar = true
		#catchable mobs 
		#due to a vanilla bug some mobs might not render correctly or at all
		mobs = ["minecraft:slime", "minecraft:bee", "minecraft:magma_cube", "iceandfire:pixie", "alexmobs:crimson_mosquito", "mysticalworld:frog", "mysticalworld:beetle", "druidcraft:lunar_moth", "druidcraft:dreadfish", "swampexpansion:slabfish", "savageandravage:creepie", "betteranimalsplus:butterfly"]
		#tinted jar catchable mobs
		tinted_jar_mobs = ["minecraft:endermite", "minecraft:slime", "minecraft:bee", "minecraft:magma_cube", "minecraft:vex", "iceandfire:pixie", "alexmobs:crimson_mosquito", "mysticalworld:frog", "mysticalworld:beetle", "druidcraft:lunar_moth", "druidcraft:dreadfish", "swampexpansion:slabfish", "savageandravage:creepie", "betteranimalsplus:butterfly"]
		#any item can work here, ideally you should only put cookies and alike
		cookies = ["minecraft:cookie", "simplefarming:peanut_butter_cookie", "farmersdelight:sweet_berry_cookie", "farmersdelight:honey_cookie"]

	#I haven't tested most of the mods included here. let me know if they work
	[blocks.cage]
		#catchable mobs
		cage_mobs = ["minecraft:endermite", "minecraft:slime", "minecraft:parrot", "minecraft:bee", "minecraft:magma_cube", "minecraft:vex", "minecraft:rabbit", "minecraft:cat", "minecraft:chicken", "minecraft:bat", "iceandfire:pixie", "minecraft:fox", "minecraft:ocelot", "alexsmobs:roadrunner", "alexsmobs:hummingbird", "alexsmobs:crimson_mosquito", "alexsmobs:rattlesnake", "alexsmobs:lobster", "alexsmobs:capuchin_monkey", "alexsmobs:warped_toad", "mysticalworld:beetle", "mysticalworld:frog", "mysticalworld:silver_fox", "mysticalworld:sprout", "mysticalworld:endermini", "mysticalworld:lava_cat", "mysticalworld:owl", "mysticalworld:silkworm", "mysticalworld:hell_sprout", "quark:toretoise", "quark:crab", "quark:foxhound", "quark:stoneling", "quark:frog", "rats:rat", "rats:piper", "rats:plague_doctor", "rats:black_death", "rats:plague_cloud", "rats:plague_beast", "rats:rat_king", "rats:demon_rat", "rats:ratlantean_spirit", "rats:ratlantean_automation", "rats:feral_ratlantean", "rats:neo_ratlantean", "rats:pirat", "rats:ghost_pirat", "rats:dutchrat", "rats:ratfish", "rats:ratlantean_ratbot", "rats:rat_baron", "goblintraders:goblin_trader", "goblintraders:vein_goblin_trader", "autumnity:snail", "buzzierbees:honey_slime", "betteranimalsplus:lammergeier", "betteranimalsplus:songbird", "betteranimalsplus:pheasant", "betteranimalsplus:squirrel", "betteranimalsplus:badger", "betteranimalsplus:turkey", "exoticbirds:roadrunner", "exoticbirds:hummingbird", "exoticbirds:woodpecker", "exoticbirds:kingfisher", "exoticbirds:toucan", "exoticbirds:macaw", "exoticbirds:magpie", "exoticbirds:kiwi", "exoticbirds:owl", "exoticbirds:gouldianfinch", "exoticbirds:gull", "exoticbirds:pigeon", "exoticbirds:penguin", "exoticbirds:duck", "exoticbirds:booby", "exoticbirds:cardinal", "exoticbirds:bluejay", "exoticbirds:robin", "exoticbirds:kookaburra", "exoticbirds:budgerigar", "exoticbirds:cockatoo", "swampexpansion:slabfish"]
		#additional mobs that you'll be able to catch with the added condition that it has to be a baby variant. No need to include the ones already in cage_mobs
		cage_baby_mobs = ["minecraft:cow", "minecraft:sheep", "minecraft:pig"]
		#allow all mobs to be captured by cages
		cage_allow_all_mobs = false

	[blocks.notice_board]
		#allow notice boards to accept and display any item, not just maps and books
		allow_any_item = false

	[blocks.sack]
		#penalize the player with slowness effecn when carring too many sacks
		sack_penality = true
		#maximum number of sacks after which the slowness effect will be applied. each multiple of this number will further slow the player down
		#Range: 0 ~ 50
		sack_increment = 2
		#additional sack slots divided by 2. Number of slots will be 5 + additional_slots*2
		#Range: 0 ~ 2
		additional_slots = 0
		#additional blocks that can support a sack
		whitelist = []

	[blocks.safe]
		#makes safes only breakable by their owner or by a player in creative
		prevent_breaking = true

	[blocks.globe]
		#how many globe trades to give to the wandering trader. If you have mods that add more trades to him you might want to increase this so it's not as rare
		#Range: 0 ~ 50
		trades = 2
		#chanche of finding a globe in a shipwreck treasure chest.
		#Range: 0.0 ~ 1.0
		shipwreck_treasure_chance = 0.25

#Configure spawning conditions
[spawns]

	[spawns.firefly]
		#Spawnable biomes
		biomes = ["minecraft:swamp", "minecraft:swamp_hills", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:dark_forest", "minecraft:dark_forest_hills", "byg:bayou", "byg:cypress_swamplands", "byg:glowshroom_bayou", "byg:mangrove_marshes", "byg:vibrant_swamplands", "byg:fresh_water_lake", "byg:grassland_plateau", "byg:wooded_grassland_plateau", "byg:flowering_grove", "byg:guiana_shield", "byg:guiana_clearing", "byg:meadow", "byg:orchard", "byg:seasonal_birch_forest", "byg:seasonal_deciduous_forest", "byg:seasonal_forest", "biomesoplenty:flower_meadow", "biomesoplenty:fir_clearing", "biomesoplenty:grove_lakes", "biomesoplenty:grove", "biomesoplenty:highland_moor", "biomesoplenty:wetland_marsh", "biomesoplenty:deep_bayou"]
		#Whitelisted mods. All biomes from said mods will be able to spawn fireflies. Use the one above for more control
		mod_whitelist = []
		#Spawn weight 
		#Set to 0 to disable spawning entirely
		#Range: 0 ~ 100
		weight = 3
		#Minimum group size
		#Range: 0 ~ 64
		min = 5
		#Maximum group size
		#Range: 0 ~ 64
		max = 9

#entities parameters
[entities]

	[entities.firefly]
		#firefly animation period
		#note that actual period will be this + a random number between 0 and 10
		#this needs to be here to allow correct despawning of the entity when it's not glowing
		#check client configs come more animation settings
		#Range: 1 ~ 200
		period = 65
		#firefly flying speed
		#Range: 0.0 ~ 10.0
		speed = 0.3
		#despawn during the day
		despawn = true

#Vanilla tweaks
[tweaks]

	[tweaks.throwable_bricks]
		#throw bricks at your foes! Might glass blocks
		enabled = true
		#additional items that will be able to be thrown (will work with any item). Items tagges as forge/ingots/bricks or nether bricks will be automatically added
		whitelist = ["biomesoplenty:mud_brick", "byg:yellow_nether_brick", "byg:blue_nether_brick"]

	[tweaks.wall_lantern]
		#allow wall lanterns placement
		enabled = true
		#mod ids of mods that have lantern block that extend the base lantern class but don't look like one
		mod_blacklist = ["extlights"]

	[tweaks.bells_tweaks]
		#ring a bell by clicking on a chain that's connected to it
		chain_ringing = true
		#max chain length that allows a bell to ring
		#Range: 0 ~ 1024
		chain_length = 32

	[tweaks.hanging_flower_pots]
		#allows you to place hanging flower pots. Works with any modded pot too
		enabled = true

	[tweaks.cake_tweaks]
		#allows you to place a cake ontop of another
		double_cake = true
		#replaces normal cake placement with a directional one
		directional_cake = true

[items]

	[items.flute]
		#radius in which an unbound flute will search pets
		#Range: 0 ~ 500
		unbound_radius = 64
		#max distance at which a bound flute will allow a pet to teleport
		#Range: 0 ~ 500
		bound_distance = 64

[comment]
	#This config is synced server side. If you are on a server you'll get its own version
	comment = true

