#Death Timer
#Range: 0 ~ 220000
DeathTimer = 24000
#Heal Time for Golden Pet Bandage
#Range: 0 ~ 120
HealTime = 20
#Auto Heal after timer
AutoHeal = false
#Show Location
ShowLoc = true
#Use world ticks otherwise chunk ticks
UseWorldTicks = false

