
[Generic]
	# Enables the debug item to right click on blocks or entities to get data about them
	enableDebugItemForBlocksAndEntities = true
	# The debug item to right click with to dump item NBT from the item to the right of it on the hotbar
	debugItemNameItems = "minecraft:blaze_rod"
	# Enables the debug item to right click with to dump data
	# from the item next to the right of it on the hotbar
	enableDebugItemForItems = true
	# The debug item to right click on blocks and entities with.
	debugItemNameBlocks = "minecraft:gold_nugget"

