
#General settings for the mod.
[general]
	#Should enchantability be shown?
	show-enchantability = true
	#Should mining efficiency be shown?
	show-efficiency = true
	#Should harvest level be shown?
	show-harvest-level = true

