
#Common configuration settings
[common]
	#This option controls if backpacks in backpacks are allowed.
	#If set to true you can put backpacks in existing backpacks and stack them together.
	#If set to false you cannot put backpacks in backpacks
	allowStackingBackpacks = false

