
[structures]
	#Biomes in which Structures cant generate in
	blacklisted_biomes = ["minecraft:ocean", "minecraft:river", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:deep_ocean", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean"]

	[structures.tower_ruin]
		#Tower Ruin Distance (in chunks) [default: 25]
		#Range: 1 ~ 500
		distance = 25
		#Tower Ruin Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Tower Ruin can NOT generate in
		biome_blacklist = []
		#Generate Tower Ruins?
		generate = true
		#Biome Types the Tower Ruin can generate in
		biome_categories = ["PLAINS", "FOREST", "EXTREME_HILLS", "TAIGA"]
		#Tower Ruin Spawn Chance [default: 0.8]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.8

	[structures.castle]
		#Castle Distance (in chunks) [default: 40]
		#Range: 1 ~ 500
		distance = 40
		#Castle Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Castle can NOT generate in
		biome_blacklist = []
		#Generate Castles?
		generate = true
		#Biome Types the Castle can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Castle Spawn Chance [default: 0.5]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.5

	[structures.player_house]
		#Desert House Distance (in chunks) [default: 30]
		#Range: 1 ~ 500
		distance = 30
		#Desert House Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Player House can NOT generate in
		biome_blacklist = []
		#Generate Player Houses?
		generate = true
		#Biome Types the Player House can generate in
		biome_categories = ["PLAINS", "FOREST", "EXTREME_HILLS", "TAIGA"]
		#Player House Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7

	[structures.forge]
		#Forge Distance (in chunks) [default: 30]
		#Range: 1 ~ 500
		distance = 30
		#Forge Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Forge can NOT generate in
		biome_blacklist = []
		#Generate Forges?
		generate = true
		#Biome Types the Forge can generate in
		biome_categories = ["PLAINS", "FOREST", "EXTREME_HILLS", "TAIGA"]
		#Forge Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7

	[structures.small_dungeon]
		#Small Dungeon Distance (in chunks) [default: 30]
		#Range: 1 ~ 500
		distance = 30
		#Small Dungeon Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Small Dungeon can NOT generate in
		biome_blacklist = []
		#Generate Small Dungeons?
		generate = true
		#Biome Types the Small Dungeon can generate in
		biome_categories = ["PLAINS", "FOREST", "EXTREME_HILLS", "TAIGA", "DESERT", "MESA", "SAVANNA", "JUNGLE", "ICY", "SWAMP"]
		#Small Dungeon Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7

	[structures.desert_house]
		#Desert House Distance (in chunks) [default: 30]
		#Range: 1 ~ 500
		distance = 30
		#Desert House Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Desert House can NOT generate in
		biome_blacklist = []
		#Generate Desert Houses?
		generate = true
		#Biome Types the Desert House can generate in
		biome_categories = ["DESERT"]
		#Desert House Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7

	[structures.global]
		#How flat does terrain need to be for surface structures to spawn? (in blocks) [default: 4]
		#Range: 0 ~ 64
		flatness_delta = 3

	[structures.castle_ruin]
		#Castle Ruin Distance (in chunks) [default: 35]
		#Range: 1 ~ 500
		distance = 35
		#Castle Ruin Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 8
		#Biomes the Castle Ruin can NOT generate in
		biome_blacklist = []
		#Generate Castle Ruins?
		generate = true
		#Biome Types the Castle Ruin can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Castle Ruin Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

