
[client]
	#If enabled, the text overlay on waystones will no longer always render at full brightness.
	disableTextGlow = false
	#The y position of the warp button in the inventory.
	teleportButtonY = 60
	#The volume of the sound played when teleporting.
	#Range: 0.0 ~ 1.0
	soundVolume = 0.3499999940395355
	#The x position of the warp button in the inventory.
	teleportButtonX = 58
	#If enabled, activated waystones will not emit particles.
	disableParticles = false
	#If enabled, JourneyMap waypoints will be created for each activated waystone.
	displayWaystonesOnJourneyMap = false
	#The x position of the warp button in the creative menu.
	creativeWarpButtonX = 88
	#The y position of the warp button in the creative menu.
	creativeWarpButtonY = 33

