
#Mekanism Generators Config. This config is synced between server and client.
[generators]
	#Peak output for the Advanced Solar Generator. Note: It can go higher than this value in some extreme environments.
	advancedSolarGeneration = "640"
	#Affects the Injection Rate, Max Temp, and Ignition Temp.
	energyPerFusionFuel = "550000"
	#Amount of energy in Joules the Bio Generator produces per tick.
	bioGeneration = "350"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	solarGeneration = "80"

	#Wind Generator Settings
	[generators.wind_generator]
		#Minimum base generation value of the Wind Generator.
		windGenerationMin = "60"
		#The list of dimension ids that the Wind Generator will not generate power in.
		windGenerationDimBlacklist = []
		#The maximum Y value that affects the Wind Generators Power generation.
		windGenerationMaxY = 90
		#Maximum base generation value of the Wind Generator.
		windGenerationMax = "300"
		#The minimum Y value that affects the Wind Generators Power generation.
		windGenerationMinY = 40

	#Turbine Settings
	[generators.turbine]
		#The number of blades on each turbine coil per blade applied.
		turbineBladesPerCoil = 4
		#The rate at which steam is vented into the turbine.
		turbineVentGasFlow = 32000.0
		#The rate at which steam is dispersed into the turbine.
		turbineDisperserGasFlow = 1280.0
		#The rate at which steam is condensed in the turbine.
		condenserRate = 64000

	#Heat Generator Settings
	[generators.heat_generator]
		#Add this amount of Joules to the energy produced by a heat generator if it is in an 'ultrawarm' dimension, in vanilla this is just the Nether.
		heatGenerationNether = "100"
		#Multiplier of effectiveness of Lava that is adjacent to the Heat Generator.
		heatGenerationLava = "30"
		#Amount of energy in Joules the Heat Generator produces per tick. heatGeneration + heatGenerationLava * lavaSides + heatGenerationNether. Note: lavaSides is how many sides are adjacent to lava, this includes the block itself if it is lava logged allowing for a max of 7 "sides".
		heatGeneration = "200"
		#The amount of lava in mB that gets consumed to transfer heatGeneration Joules to the Heat Generator.
		#Range: 1 ~ 24000
		heatGenerationFluidRate = 10

	#Fission Reactor Settings
	[generators.fission_reactor]
		#The heat capacity added to a Fission Reactor by a single casing block. Increase to require more energy to raise the reactor temperature.
		casingHeatCapacity = 1000.0
		#The chance of a meltdown occurring once damage passes 100%. Will linearly scale as damage continues increasing.
		#Range: 0.0 ~ 1.0
		meltdownChance = 0.001
		#Whether catastrophic meltdowns can occur from Fission Reactors. If disabled instead of melting down the reactor will turn off and not be able to be turned back on until the damage level decreases.
		meltdownsEnabled = true
		#How much radioactivity of fuel/waste contents are multiplied during a meltdown.
		meltdownRadiationMultiplier = 50.0
		#The average surface area of a Fission Reactor's fuel assemblies to reach 100% boil efficiency. Higher values make it harder to cool the reactor.
		#Range: 1.0 ~ 1.7976931348623157E308
		surfaceAreaTarget = 4.0
		#Amount of energy created (in heat) from each whole mB of fission fuel.
		energyPerFissionFuel = "1000000"
		#The default burn rate of the fission reactor.
		#Range: 0.001 ~ 1.0
		defaultBurnRate = 0.1
		#The burn rate increase each fuel assembly provides. Max Burn Rate = fuelAssemblies * burnPerAssembly
		#Range: 1 ~ 1000000
		burnPerAssembly = 1
		#Damage to reset the reactor to after a meltdown.
		#Range: 0.0 ~ 100.0
		postMeltdownDamage = 75.0

	#Hohlraum Settings
	[generators.hohlraum]
		#Amount of DT-Fuel Hohlraum can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 1
		#Hohlraum capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 10

	#Fusion Settings
	[generators.fusion_reactor]
		#The fraction of the heat dissipated from the case that is converted to Joules.
		#Range: 0.0 ~ 1.0
		thermocoupleEfficiency = 0.014
		#The fraction fraction of heat from the casing that can be transferred to all sources that are not water. Will impact max heat, heat transfer to thermodynamic conductors, and power generation.
		#Range: 0.001 ~ 1.0
		casingThermalConductivity = 0.1
		#The fraction of the heat from the casing that is dissipated to water when water cooling is in use. Will impact max heat, and steam generation.
		#Range: 0.0 ~ 1.0
		waterHeatingRatio = 0.3

