
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 10140372
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false

[create]
	#The byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

