
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 9603169
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

