
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 60000000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 10000000
	#Range: 0 ~ 9000000000000000000
	basicCap = 1000000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 25000000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 140000000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 4000000
	#Range: 0 ~ 9000000000000000000
	starterCap = 100000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 100000
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 200
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 2500
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 8000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 50000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 20000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 400000

