
#General settings
[general]
	#Is Enabled?
	enabled = true
	#Cost
	#Range: > -2147483648
	cost = 15
	#Is Starter Glyph?
	starter = false
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2147483647
	#Limits the number of times a given augment may be applied to a given effect
	#Example entry: "amplify=5"
	augment_limits = []
	#Base range in blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	base_range = 16.0
	#Bonus range per augment
	#Range: 0.0 ~ 1.7976931348623157E308
	bonus_range_per_augment = 16.0

