
["General Options"]
	#
	#When set to true will display some debug info in console. [true/false]
	showDebugInfo = false
	#
	#When set to true an en_us.json file will be generated for the bees. [true/false] 
	# This file will be overwritten every time the mod loads. 
	# The generated names are based on the bee jsons. 
	#This is best used by pack devs as a one-time run.
	generateEnglishLang = false

