
["Bee Options"]
	#
	#Should bees die from stinging?
	#Note: Bees will continue to attack until they are no longer angry!
	beeDiesFromSting = true
	#
	#Should bees die when their Y-level is below 0?
	#Note: If false, bees will get stuck just below y-0 and not move. **May not be useful with new AI**
	beeDiesInVoid = true
	#
	#This value scales the child size for all Resource Bees.
	#Range: 1.0 ~ 2.0
	global_child_size_modifier = 1.0
	#
	#This value scales the bee size for all Resource Bees. 
	#Note: Setting the value in bee JSON overrides this value.
	#Range: 0.5 ~ 2.0
	global_bee_size_modifier = 1.0
	#
	#Should bees inflict poison damage?
	#Note: Poison is only inflicted if a bee has not been given a trait with a special damage output.
	#Set to false if you want to configure bees individually.
	beesInflictPoison = true

["Apiary Options"]
	#
	#Maximum number of UNIQUE bees allowed in the Apiary.
	#Range: 1 ~ 16
	apiaryMaxBees = 9
	#
	#Tier 3 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierThreeApiaryOutput = "BLOCK"
	#
	#Tier 4 Apiary Output Quantity
	#Range: > 1
	tierFourApiaryQuantity = 2
	#
	#Tier 2 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierTwoApiaryOutput = "COMB"
	#
	#Tier 2 Apiary Output Quantity
	#Range: > 1
	tierTwoApiaryQuantity = 6
	#
	#Tier 3 Apiary Output Quantity
	#Range: > 1
	tierThreeApiaryQuantity = 1
	#
	#Tier 1 Apiary Output Quantity
	#Range: > 1
	tierOneApiaryQuantity = 3
	#
	#Tier 4 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierFourApiaryOutput = "BLOCK"
	#
	#Maximum breed time before upgrades are applied.
	#Range: 1200 ~ 4800
	apiaryMaxBreedTime = 3200
	#
	#Tier 1 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierOneApiaryOutput = "COMB"

["Centrifuge Options"]
	#
	#Amount of hunger the player uses per click on mechanical centrifuge.
	#Range: 0.0 ~ 1.0
	mechanicalCentrifugePlayerExhaustion = 0.1
	#
	#Global recipe time for generated centrifuge recipes
	#This does not affect recipes that are not auto generated by us.
	#Time is in ticks.
	#Range: 100 ~ 2400
	globalCentrifugeRecipeTime = 200
	#
	#Tick reduction applied to centrifuge recipes
	#This does not affect recipes that are not auto generated by us.
	#NOTE: Lowest recipe time allowed is 5 ticks regardless of values provided.
	#Range: 10 ~ 1200
	multiblockRecipeTimeReduction = 150
	#
	#Centrifuge Max energy storage.
	#The Centrifuge Multiblocks max energy storage is 5x this amount
	#Range: 1000 ~ 1000000
	maxCentrifugeRf = 10000
	#
	#Makes it so multiblock centrifuge can only do multiblock recipes. [true/false]
	multiblockRecipesOnly = false
	#
	#RF/t consumed by the centrifuge when processing recipes. Mutliblock Centrifuge cuts this value in half.
	#Range: 2 ~ 1000
	centrifugeRfPerTick = 2
	#
	#Sets the max RF/t that the centrifuge can receive. This should ideally be set higher than centrifugeRfPerTick.
	#Range: 100 ~ 10000
	maxCentrifugeReceiveRate = 100

["Beehive Options"]
	#
	#Base honeycomb harvest amount 
	#(THIS * TIER_MODIFIER = MAX_COMBS) for a range of 5 -> 64
	#Range: 5 ~ 16
	hiveMaxCombs = 5
	#
	#Set to false if you want the player to only be able to get honeycombs from the beehive using the scraper [true/false]
	allowShears = true
	#
	#Maximum number of bees in the base tier hive. 
	#(THIS * TIER_MODIFIER = MAX_BEES) for a range of 4 -> 16
	#Range: 1 ~ 4
	hiveMaxBees = 4

["General Options"]
	#
	#Sets the max durability for the smoker
	#Range: 100 ~ 5000
	smokerDurability = 1000
	#
	#Set this to false when you want to overwrite the default provided Biome Dictionary files. [true/false]
	#This should be run at least once for initial generation.
	generateBiomeDictionaries = true
	#
	#Set this to false when you want to use our custom Biome Dictionary system. [true/false]
	#At a later time we will look into either combining with the Forge system or making the Forge system data pack capable.
	useForgeBiomeDictionaries = false
	#
	#Set to true if you want easter egg bees to generate (WIP) [true/false]
	#The only easter egg bee currently available is the Oreo bee
	enableEasterEggBees = true
	#
	#Set this to false when you want to overwrite the default bee files. [true/false]
	#This should be run at least once for initial generation.
	generateDefaults = false
	#
	#Set to true to hide certain data in the Beepedia until the player has unlocked the bee. [true/false]
	beepediaHideLocked = false

["Honey Generator Options"]
	#
	#Amount of honey consumed in mb/t.
	#Range: 1 ~ 50
	honeyDrainAmount = 5
	#
	#Amount of energy transferred out of the generator in rf/t.
	#Range: 50 ~ 500
	energyTransferAmount = 100
	#
	#Maximum internal honey capacity.
	#Range: 1000 ~ 100000
	maxTankCapacity = 10000
	#
	#Amount of rf/t generated.
	#Range: 0 ~ 500
	energyFillAmount = 250
	#
	#Amount of honey generated in mb/t. 1 bottle = 250mb honey
	#Range: 1 ~ 50
	honeyFillAmount = 10
	#
	#Maximum internal energy buffer.
	#Range: 10000 ~ 1000000
	maxEnergyCapacity = 100000

["Spawning Options"]
	#
	#Chance for nest to spawn when generating chunks in nether category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	nether_nest_generation_chance = 8
	#The value added to weight for bees in a flower forests
	#Range: 0 ~ 9
	beesMoreCommonInFlowerForests = 4
	#
	#Chance for nest to spawn when generating chunks in overworld category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	overworld_nest_generation_chance = 64
	#
	#Chance for nest to spawn when generating chunks in end category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	end_nest_generation_chance = 32
	#
	#Should bee nests generate in world? 
	#Note: They will only generate in biomes where bees can spawn
	generateBeeNests = true

["Recipe Options"]
	#
	#Set to false if you don't want the honeycomb block recipes to be auto generated [true/false]
	honeycombBlockRecipes = true
	#
	#Set to false if you don't want the centrifuge recipes to be auto generated [true/false]
	centrifugeRecipes = true

["Honeycomb Options"]
	#
	#The amount of hunger restored when eating a honeycomb.
	#Range: 0 ~ 8
	honeycombHunger = 1
	#
	#The amount of saturation restored when eating a honeycomb.
	#Range: 0.0 ~ 8.0
	honeycombSaturation = 0.6

["Honey Options"]
	#
	#Set to false if you don't want the custom honey fluids to be generated [true/false]
	generateHoneyFluids = true
	#
	#Set to false if you don't want the custom honey blocks to be generated [true/false]
	generateHoneyBlocks = true
	#
	#Should honey block recipes be generated? [true/false]
	honeyBlockRecipes = true

["Ender Beecon Options"]
	#
	#If true, the below values will be multiplied with the base value, if false they will be added instead.
	beeconDoMultiplier = true
	#
	#Multiplier for the drain rate for the Ender Beecon when the Calming effect is active.
	#Range: 1.0 ~ 128.0
	beeconCalmingValue = 2.0
	#
	#Multiplier for the drain rate for the Ender Beecon when the Water Breathing effect is active.
	#Range: 1.0 ~ 128.0
	beeconWaterBreathingValue = 1.5
	#
	#Multiplier for the drain rate for the Ender Beecon when the Fire Resistance effect is active.
	#Range: 1.0 ~ 128.0
	beeconFireResistanceValue = 2.0
	#
	#Multiplier for the drain rate for the Ender Beecon when the Regeneration effect is active.
	#Range: 1.0 ~ 128.0
	beeconRegenerationValue = 2.5
	#
	#Range in blocks added for each effect that is currently active.
	#Range: 1 ~ 25
	beeconRangePerEffect = 10
	#
	#The base drain rate for the Ender Beecon when an effect is active.
	#Range: 1 ~ 128
	beeconBaseDrain = 1
	#
	#The amount of fluid per tick the Ender Beecon can pull from below blocks.
	#Range: 1 ~ 16000
	beeconPullAmount = 250

["Mod Options"]
	#Set this to true if you wish to live life on the edge!
	#Seriously though it is recommended this only be used for testing purposes!!!
	bypassPerformantCheck = false

