
["Bee Options"]
	#
	#Should bees die from stinging?
	#Note: Bees will continue to attack until they are no longer angry!
	beeDiesFromSting = true
	#
	#Should bees die when their Y-level is below 0?
	#Note: If false, bees will get stuck just below y-0 and not move.
	beeDiesInVoid = true
	#
	#This value scales the child size for all Resource Bees.
	#Range: 1.0 ~ 2.0
	global_child_size_modifier = 1.0
	#
	#This value scales the bee size for all Resource Bees. 
	#Note: Setting the value in bee JSON overrides this value.
	#Range: 0.5 ~ 2.0
	global_bee_size_modifier = 1.0

["Apiary Options"]
	#
	#Maximum number of UNIQUE bees allowed in the Apiary.
	#Range: 1 ~ 16
	apiaryMaxBees = 9
	#
	#Tier 3 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierThreeApiaryOutput = "BLOCK"
	#
	#Tier 4 Apiary Output Quantity
	#Range: > 1
	tierFourApiaryQuantity = 8
	#
	#Tier 2 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierTwoApiaryOutput = "COMB"
	#
	#Tier 2 Apiary Output Quantity
	#Range: > 1
	tierTwoApiaryQuantity = 16
	#
	#Tier 3 Apiary Output Quantity
	#Range: > 1
	tierThreeApiaryQuantity = 4
	#
	#Tier 1 Apiary Output Quantity
	#Range: > 1
	tierOneApiaryQuantity = 8
	#
	#Tier 4 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierFourApiaryOutput = "BLOCK"
	#
	#Maximum breed time before upgrades are applied.
	#Range: 1200 ~ 4800
	apiaryMaxBreedTime = 2400
	#
	#Tier 1 Apiary Output
	#Allowed Values: COMB, BLOCK
	tierOneApiaryOutput = "COMB"

["Centrifuge Options"]
	#
	#Recipe time for generated centrifuge recipes
	#This does not affect recipes that are not auto generated by us.
	#Time is in seconds.
	#Range: 1 ~ 120
	centrifugeMultiblockRecipeTime = 5
	#
	#Amount of hunger the player uses per click on mechanical centrifuge.
	#Range: 0.0 ~ 1.0
	mechanicalCentrifugePlayerExhaustion = 0.1
	#
	#Centrifuge Max energy storage.
	#The Centrifuge Multiblocks max energy storage is 5x this amount
	#Range: 1000 ~ 1000000
	maxCentrifugeRf = 10000
	#
	# Makes it so multiblock centrifuge can only do multiblock recipes. [true/false]
	multiblockRecipesOnly = false
	#
	#Recipe time for generated centrifuge recipes
	#This does not affect recipes that are not auto generated by us.
	#Time is in seconds.
	#Range: 1 ~ 120
	centrifugeRecipeTime = 10
	#
	#Centrifuge RF per tick.
	#Range: 1 ~ 100
	centrifugeRfPerTick = 1

["Beehive Options"]
	#
	#Base honeycomb harvest amount 
	#(THIS * TIER_MODIFIER = MAX_COMBS) for a range of 5 -> 64
	#Range: 5 ~ 16
	hiveMaxCombs = 5
	#
	#Set to false if you want the player to only be able to get honeycombs from the beehive using the scraper [true/false]
	allowShears = true
	#
	#Maximum number of bees in the base tier hive. 
	#(THIS * TIER_MODIFIER = MAX_BEES) for a range of 4 -> 16
	#Range: 1 ~ 4
	hiveMaxBees = 4

["General Options"]
	#
	#Sets the max durability for the smoker
	#Range: 100 ~ 5000
	smokerDurability = 1000
	#
	#Set this to false when you want to overwrite the default biome dictionary files. [true/false]
	#This should be run at least once for initial generation.
	generateBiomeDictionaries = true
	#
	#Set to true if you want easter egg bees to generate (WIP) [true/false]
	enableEasterEggBees = true
	#
	#Set this to false when you want to overwrite the default bee files. [true/false]
	#This should be run at least once for initial generation.
	generateDefaults = true

["Spawning Options"]
	#
	#Chance for nest to spawn when generating chunks in nether category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	nether_nest_generation_chance = 8
	#
	#Chance for nest to spawn when generating chunks in overworld category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	overworld_nest_generation_chance = 48
	#
	#Chance for nest to spawn when generating chunks in end category biomes. [1/x]
	#A higher value means the nest is less likely to spawn.
	#Range: 4 ~ 100
	end_nest_generation_chance = 32
	#
	#Should bee nests generate in world? 
	#Note: They will only generate in biomes where bees can spawn
	generateBeeNests = true

["Recipe Options"]
	#
	#Set to false if you don't want the honeycomb block recipes to be auto generated [true/false]
	honeycombBlockRecipes = true
	#
	#Set to false if you don't want the centrifuge recipes to be auto generated [true/false]
	centrifugeRecipes = true

["Honeycomb Options"]
	#
	#The amount of hunger restored when eating a honeycomb.
	#Range: 0 ~ 8
	honeycombHunger = 1
	#
	#The amount of saturation restored when eating a honeycomb.
	#Range: 0.0 ~ 8.0
	honeycombSaturation = 0.6

