#
# How rare are Grassy Igloos in Plains and Forests.
# 1 for spawning in most chunks and 1001 for no spawn.
#Range: 1 ~ 1001
grassyIglooMaxChunkDistance = 20
#
# How rare are Stone Igloos in Giant Tree Taiga biomes.
# 1 for spawning in most chunks and 1001 for no spawn.
#Range: 1 ~ 1001
stoneIglooMaxChunkDistance = 20

