
[Spawnrate]
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Birch biomes with a Birch themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	birchMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Jungle biomes with a Jungle themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	jungleMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Desert biomes with a Desert themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	desertMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Mountain (Extreme Hills) biomes with a Stone themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	stoneMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Savanna biomes with a Savanna themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	savannaMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Snowy/Icy biomes with an Ice themed Mineshaft.
	# Note: Snowy Taiga Biomes will get Ice Mineshaft instead of Taiga theme.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	icyMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Ocean biomes with an Ocean themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	oceanMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Taiga biomes with a Taiga themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	taigaMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Dark Forests with a dark oak themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	darkForestMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 is no Mineshafts while 1000 is max spawnrate.
	# Replace Mineshafts in Swamps with a swampy themed Mineshaft.
	# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
	#Range: 0.0 ~ 1000.0
	swampMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 for no Mineshafts and 1000 for max spawnrate.
	# Adds End themed Mineshafts to End biomes outside the Enderdragon island.
	#Range: 0.0 ~ 1000.0
	endMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 for no Mineshafts and 1000 for max spawnrate.
	# Adds Nether themed Mineshafts to non-crimson and non-warped Nether biomes.
	#Range: 0.0 ~ 1000.0
	netherMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 for no Mineshafts and 1000 for max spawnrate.
	# Adds Crimson themed Mineshafts to Crimson Nether biomes.
	#Range: 0.0 ~ 1000.0
	crimsonMineshaftSpawnrate = 40.0
	#
	# Controls how often Mineshafts will spawn. 0 for no Mineshafts and 1000 for max spawnrate.
	# Adds Warped themed Mineshafts to Warped Nether biomes.
	#Range: 0.0 ~ 1000.0
	warpedMineshaftSpawnrate = 40.0

["Min height"]
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	birchMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	jungleMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	desertMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	stoneMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	savannaMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	icyMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	oceanMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	taigaMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	darkForestMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	swampMineshaftMinHeight = 8
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	endMineshaftMinHeight = 30
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	netherMineshaftMinHeight = 6
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	crimsonMineshaftMinHeight = 6
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	#Range: 5 ~ 255
	warpedMineshaftMinHeight = 6

["Max height"]
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	birchMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	jungleMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	desertMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	stoneMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	savannaMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	icyMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	oceanMineshaftMaxHeight = 26
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	taigaMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	darkForestMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	swampMineshaftMaxHeight = 45
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	endMineshaftMaxHeight = 40
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	netherMineshaftMaxHeight = 17
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	crimsonMineshaftMaxHeight = 14
	#
	# Minimum Y height that this mineshaft can spawn at.
	# Note: The mineshaft will spawn between min and max y height set in config.
	# Setting this to below min height config will make mineshaft spawn only at min height.
	#Range: 5 ~ 255
	warpedMineshaftMaxHeight = 14

[Size]
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	birchMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	jungleMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	desertMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	stoneMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	savannaMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	icyMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	oceanMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	taigaMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	darkForestMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	swampMineshaftSize = 9
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	endMineshaftSize = 11
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	netherMineshaftSize = 10
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	crimsonMineshaftSize = 10
	#
	# Size of the mineshaft. This is how many pieces long a branch can be from the start piece.
	#Range: 1 ~ 30
	warpedMineshaftSize = 10

[Misc]
	#
	# Add End Mineshafts to End Barrens and End Islands biome.
	barrensIslandsEndMineshafts = false

