
[Outposts]
	#
	# How rare are Nether Brick Outposts in non-warped Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherBrickOutpostMaxChunkDistance = 34
	#
	# How rare are Warped Outposts in Warped Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	warpedOutpostMaxChunkDistance = 34
	#
	# How rare are Crimson Outposts in Warped Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	crimsonOutpostMaxChunkDistance = 34
	#
	# How rare are Birch Outposts in Birch Forest biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostBirchMaxChunkDistance = 45
	#
	# How rare are Jungle Outposts in Jungle biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostJungleMaxChunkDistance = 45
	#
	# How rare are Giant Tree Taiga Outposts in Giant Tree Taiga biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostGiantTreeTaigaMaxChunkDistance = 45
	#
	# How rare are Desert Outposts in Desert biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostDesertMaxChunkDistance = 45
	#
	# How rare are Badlands Outposts in Badlands biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostBadlandsMaxChunkDistance = 45
	#
	# How rare are Snowy Outposts in snowy biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostSnowyMaxChunkDistance = 45
	#
	# How rare are Icy Outposts in icy/extremely cold biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostIcyMaxChunkDistance = 41
	#
	# How rare Taiga Icy Outposts in forest biomes that are not birch or dark forest biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostOakMaxChunkDistance = 45
	#
	# How rare Taiga Icy Outposts in non-snowy and non-giant taiga biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostTaigaMaxChunkDistance = 45
	#
	# How rare are End Outposts in End biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	outpostEndMaxChunkDistance = 61

