#
# How rare are Nether Pyramids in Nether.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherPyramidMaxChunkDistance = 37
#
# How rare are Badlands Pyramid in non-plateau Badlands biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
badlandsPyramidMaxChunkDistance = 40
#
# How rare are Snowy Pyramid in snowy biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidSnowyMaxChunkDistance = 40
#
# How rare are End Pyramid in End biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidEndMaxChunkDistance = 68
#
# How rare are Icy Pyramid in super cold or icy biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidIcyMaxChunkDistance = 37
#
# How rare are Jungle Pyramid in Jungle biomes. 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidJungleMaxChunkDistance = 44
#
# How rare are Mushroom Pyramid in Mushroom biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidMushroomMaxChunkDistance = 24
#
# How rare are Ocean Pyramid in Ocean biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidOceanMaxChunkDistance = 40
#
# How rare are Giant Tree Taiga Pyramid in Giant Tree Taiga biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidGiantTreeTaigaMaxChunkDistance = 40
#
# How rare are Flower Forest Pyramid in Flower Forest biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
pyramidFlowerForestMaxChunkDistance = 36

