#
# How rare are Nether Ruins. 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
ruinsNetherMaxChunkDistance = 35
#How rare are Warm Land Ruins in Plains, Forests, Swamps, and non-snowy Taiga biomes.
#
#1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
ruinsLandWarmMaxChunkDistance = 36
#How rare are Hot Land Ruins in Desert biomes.
#
#1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
ruinsLandHotMaxChunkDistance = 39

