
[Shipwrecks]
	#
	# How rare are End Shipwreck in End Highlands biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	endShipwreckMaxChunkDistance = 24
	#
	# How rare are Nether Bricks Shipwreck in any non-warped or non-crimson Nether biome.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherBricksShipwreckMaxChunkDistance = 51
	#
	# How rare are Crimson Shipwreck in Crimson Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	crimsonShipwreckMaxChunkDistance = 41
	#
	# How rare are Warped Shipwreck in Warped Nether biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	warpedShipwreckMaxChunkDistance = 41

