#
# How rare are Nether Temples in Nether Wastelands.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherWastelandTempleMaxChunkDistance = 27
#
# How rare are Nether Basalt Temples in Nether Basalt Delta biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherBasaltTempleMaxChunkDistance = 27
#
# How rare are Nether Crimson Temples in Nether Crimson Forest.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherCrimsonTempleMaxChunkDistance = 27
#
# How rare are Nether Crimson Temples in Nether Warped Forest.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherWarpedTempleMaxChunkDistance = 27
#
# How rare are Nether Soul Temples in Nether Soul Sand Valley.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherSoulTempleMaxChunkDistance = 27

