#
# Add Oak Witch Huts to modded Forest biomes that are not birch or dark oak.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
witchHutsOakMaxChunkDistance = 48
#
# Add Taiga Witch Huts to modded Taiga biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
witchHutsTaigaMaxChunkDistance = 48
#
# Add Giant Tree Taiga Witch Huts to modded Giant Tree Taiga biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
witchHutsGiantTreeTaigaMaxChunkDistance = 48
#
# Add Birch Witch Huts to modded Birch biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
witchHutsBirchMaxChunkDistance = 48
#
# Add Dark Forest Witch Huts to modded Dark Forest biomes.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
witchHutsDarkForestMaxChunkDistance = 48

