
[The_End]
	#
	#Does BYG control The End?
	ControlEnd = true
	#
	#End Biome Size.
	#Default: 3
	#Range: 0 ~ 10
	IslandBiomeSize = 3
	#
	#End Biome Size
	#Default: 3
	#Range: 0 ~ 10
	EndBiomeSize = 3

	[The_End.Void]
		#
		#Void Biome(where small end islands generate in vanilla) size.
		#Default: 3
		#Range: 0 ~ 10
		VoidBiomeSize = 2

[Overworld]

	[Overworld.Ores]

		[Overworld.Ores.Pendorite]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			PendoritePerChunk = 10
			#
			#Generate Pendorite Ore? Only spawns in Forest Fault.
			GeneratePendorite = false
			#
			#Y level to start generating at.
			#Default: 56
			#Range: 1 ~ 256
			PendoriteY = 56
			#
			#Size of the clusters.
			#Default: 4
			#Range: 1 ~ 100
			PendoriteSize = 4

		#Datapacks can and will override all values in the "Ore" category so keep that in mind!
		[Overworld.Ores.Ametrine]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			AmetrinePerChunk = 10
			#
			#Size of the clusters.
			#Default: 4
			#Range: 1 ~ 100
			AmetrineSize = 4
			#
			#Generate Ametrine Ore? Only spawns in Guiana Shield, Stone Forest, and Pointed Stone Forest!
			GenerateAmetrine = false
			#
			#Y level to start generating at.
			#Default: 56
			#Range: 1 ~ 256
			AmetrineY = 56

	[Overworld.Stones]

		[Overworld.Stones.Scoria_Stone]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			ScoriaStonePerChunk = 1
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			ScoriaStoneY = 63
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			ScoriaStoneSize = 32
			#
			#Generate Scoria Stone?
			GenerateScoriaStone = false

		[Overworld.Stones.Soap_Stone]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			SoapStonePerChunk = 1
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			SoapStoneSize = 32
			#
			#Generate Soap Stone?
			GenerateSoapStone = false
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			SoapStoneY = 63

		#Datapacks can and will override all values in the "Stone" category so keep that in mind!
		[Overworld.Stones.Rocky_Stone]
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			RockyStoneY = 63
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			RockyStoneSize = 32
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			RockyStonePerChunk = 1
			#
			#Generate Rocky Stone?
			GenerateRockyStone = false

[The_Nether]
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically! When set to false, you will need to manually add datapack entries.
	#Default: true
	isBlacklistNether = true
	#
	#Nether Biome Size
	#Default: 3
	#Range: 0 ~ 10
	NetherBiomeSize = 3
	#
	#Does BYG control The Nether?
	ControlNether = true
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistNether" value.
	#NO SPACES AFTER COMMAS!
	#Default: ""
	BlacklistNether = ""

