
[MachineResourceProductionConfig]

	[MachineResourceProductionConfig.BlockBreakerConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000

	[MachineResourceProductionConfig.FluidPlacerConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 16000
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000

	[MachineResourceProductionConfig.SludgeRefinerConfig]
		#Amount of Power Consumed per Tick - Default: [40FE]
		powerPerTick = 500
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Sludge] - Default: [8000mB]
		maxSludgeTankSize = 16000

	[MachineResourceProductionConfig.MechanicalDirtConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 800000
		#Max Amount of Stored Fluid [Meat] - Default: [8000mB]
		maxMeatTankSize = 4000
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 8000

	[MachineResourceProductionConfig.FluidCollectorConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Output] - Default: [8000mB]
		maxOutputTankSize = 16000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 100

	[MachineResourceProductionConfig.ResourcefulFurnaceConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 500
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Essence] - Default: [8000mB]
		maxEssenceTankSize = 16000

	[MachineResourceProductionConfig.MarineFisherConfig]
		#Max Stored Power [FE] - Default: [20000 FE]
		maxStoredPower = 2000000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [5000FE]
		powerPerOperation = 20000

	[MachineResourceProductionConfig.SporeRecreatorConfig]
		#Amount of Power Consumed per Tick - Default: [40FE]
		powerPerTick = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 100000
		#Max Amount of Stored Fluid [Water] - Default: [8000mB]
		maxWaterTankSize = 8000

	[MachineResourceProductionConfig.BlockPlacerConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000

	[MachineResourceProductionConfig.DyeMixerConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 30
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineResourceProductionConfig.MaterialStoneWorkFactoryConfig]
		#Amount of Power Consumed per Tick - Default: [60FE]
		powerPerTick = 2000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 200000
		#Max Amount of Stored Fluid [Water] - Default: [2000mB]
		maxWaterTankSize = 2000
		#Max Amount of Stored Fluid [Lava] - Default: [2000mB]
		maxLavaTankSize = 2000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [60 (3s)]
		maxProgress = 60

	[MachineResourceProductionConfig.WaterCondensatorConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Water] - Default: [8000mB]
		maxWaterTankSize = 16000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000

	[MachineResourceProductionConfig.LaserDrillConfig]
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 50000000
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [50 (2.5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [1000FE]
		powerPerOperation = 500000

	[MachineResourceProductionConfig.FluidLaserBaseConfig]
		#Max progress of the machine
		maxProgress = 20
		
	[MachineResourceProductionConfig.OreLaserBaseConfig]
		#How much weight of an item the catalyst will increase
		catalystModifier = 8
		#Max progress of the machine
		maxProgress = 200

	[MachineResourceProductionConfig.FermentationStationConfig]
		#Amount of Power Consumed per Tick - Default: [40FE]
		powerPerTick = 400
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 20000
		#Amount of ticks for 2x production - Default: [20 * 5 FE]
		ticksFor2XProduction = 300
		#Amount of ticks for 3x production - Default: [20 * 45 FE]
		ticksFor3XProduction = 600
		#Amount of ticks for 4x production - Default: [20 * 60 * 2 FE]
		ticksFor4XProduction = 3600
		#Amount of ticks for 5x production - Default: [20 * 60 * 5 FE]
		ticksFor5XProduction = 6000

	[MachineResourceProductionConfig.FluidSievingMachineConfig]
		#Progress bar size [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 90
		#Amount of Power Consumed per Tick - Default: [40FE]
		powerPerTick = 400
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 20000
		#Max Amount of Stored Fluid - Default: [8000mB]
		maxTankSize = 16000

	[MachineResourceProductionConfig.WashingFactoryConfig]
		#Progress bar size [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 90
		#Amount of Power Consumed per Tick - Default: [60FE]
		powerPerTick = 400
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 20000
		#Max Amount of Stored Fluid [Meat] - Default: [8000mB]
		maxTankSize = 8000
		#Max Amount of Output Fluid  - Default: [8000mB]
		maxOutputSize = 16000

	[MachineResourceProductionConfig.HydroponicBedConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Operation - Default: [1000FE]
		powerPerOperation = 500
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 50000

